/*
 Copyright (C) Giuliano Catrambone (giuliano.catrambone@catrasoftware.it)

 This program is free software; you can redistribute it and/or 
 modify it under the terms of the GNU General Public License 
 as published by the Free Software Foundation; either 
 version 2 of the License, or (at your option) any later 
 version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

 Commercial use other than under the terms of the GNU General Public
 License is allowed only after express negotiation of conditions
 with the authors.
*/


#include "MP4FileErrors.h"


ErrMsgBase:: ErrMsgsInfo MP4FileErrorsStr = {

	// MP4Property
	MP4F_MP4PROPERTY_INIT_FAILED,
		"The init method of the MP4Property class failed",
	MP4F_MP4PROPERTY_GETNAME_FAILED,
		"The getName method of the MP4Property class failed",
	MP4F_MP4PROPERTY_GETVALUE_FAILED,
		"The getValue method of the MP4Property class failed",
	MP4F_MP4PROPERTY_SETVALUE_FAILED,
		"The setValue method of the MP4Property class failed",
	MP4F_MP4PROPERTY_INCREMENTVALUE_FAILED,
		"The incrementValue method of the MP4Property class failed",
	MP4F_MP4PROPERTY_GETTYPE_FAILED,
		"The getType method of the MP4Property class failed",
	MP4F_MP4PROPERTY_WRITE_FAILED,
		"The write method of the MP4Property class failed",
	MP4F_MP4PROPERTY_PROPERTYTYPEWRONG,
		"Property type wrong",

	// MP4UInteger8BitsProperty
	MP4F_MP4UINTEGER8BITSPROPERTY_INIT_FAILED,
		"The init method of the MP4UInteger8BitsProperty class failed",
	MP4F_MP4UINTEGER8BITSPROPERTY_GETSIZE_FAILED,
		"The getSize method of the MP4UInteger8BitsProperty class failed",
	MP4F_MP4UINTEGER8BITSPROPERTY_WRITE_FAILED,
		"The write method of the MP4UInteger8BitsProperty class failed",
	MP4F_MP4UINTEGER8BITSPROPERTY_PRINTONSTDOUTPUT_FAILED,
	"The printOnStdOutput method of the MP4UInteger8BitsProperty class failed",
	MP4F_MP4UINTEGER8BITSPROPERTY_APPENDDUMP_FAILED,
		"The appendDump method of the MP4UInteger8BitsProperty class failed",

	// MP4UInteger16BitsProperty
	MP4F_MP4UINTEGER16BITSPROPERTY_INIT_FAILED,
		"The init method of the MP4UInteger16BitsProperty class failed",
	MP4F_MP4UINTEGER16BITSPROPERTY_GETSIZE_FAILED,
		"The getSize method of the MP4UInteger16BitsProperty class failed",
	MP4F_MP4UINTEGER16BITSPROPERTY_WRITE_FAILED,
		"The write method of the MP4UInteger16BitsProperty class failed",
	MP4F_MP4UINTEGER16BITSPROPERTY_PRINTONSTDOUTPUT_FAILED,
	"The printOnStdOutput method of the MP4UInteger16BitsProperty class failed",
	MP4F_MP4UINTEGER16BITSPROPERTY_APPENDDUMP_FAILED,
		"The appendDump method of the MP4UInteger16BitsProperty class failed",

	// MP4UInteger24BitsProperty
	MP4F_MP4UINTEGER24BITSPROPERTY_INIT_FAILED,
		"The init method of the MP4UInteger24BitsProperty class failed",
	MP4F_MP4UINTEGER24BITSPROPERTY_GETSIZE_FAILED,
		"The getSize method of the MP4UInteger24BitsProperty class failed",
	MP4F_MP4UINTEGER24BITSPROPERTY_WRITE_FAILED,
		"The write method of the MP4UInteger24BitsProperty class failed",
	MP4F_MP4UINTEGER24BITSPROPERTY_PRINTONSTDOUTPUT_FAILED,
	"The printOnStdOutput method of the MP4UInteger24BitsProperty class failed",
	MP4F_MP4UINTEGER24BITSPROPERTY_APPENDDUMP_FAILED,
		"The appendDump method of the MP4UInteger24BitsProperty class failed",

	// MP4UInteger32BitsProperty
	MP4F_MP4UINTEGER32BITSPROPERTY_INIT_FAILED,
		"The init method of the MP4UInteger32BitsProperty class failed",
	MP4F_MP4UINTEGER32BITSPROPERTY_GETSIZE_FAILED,
		"The getSize method of the MP4UInteger32BitsProperty class failed",
	MP4F_MP4UINTEGER32BITSPROPERTY_WRITE_FAILED,
		"The write method of the MP4UInteger32BitsProperty class failed",
	MP4F_MP4UINTEGER32BITSPROPERTY_PRINTONSTDOUTPUT_FAILED,
	"The printOnStdOutput method of the MP4UInteger32BitsProperty class failed",
	MP4F_MP4UINTEGER32BITSPROPERTY_APPENDDUMP_FAILED,
		"The appendDump method of the MP4UInteger32BitsProperty class failed",

	// MP4UInteger64BitsProperty
	MP4F_MP4UINTEGER64BITSPROPERTY_INIT_FAILED,
		"The init method of the MP4UInteger64BitsProperty class failed",
	MP4F_MP4UINTEGER64BITSPROPERTY_GETSIZE_FAILED,
		"The getSize method of the MP4UInteger64BitsProperty class failed",
	MP4F_MP4UINTEGER64BITSPROPERTY_WRITE_FAILED,
		"The write method of the MP4UInteger64BitsProperty class failed",
	MP4F_MP4UINTEGER64BITSPROPERTY_PRINTONSTDOUTPUT_FAILED,
	"The printOnStdOutput method of the MP4UInteger64BitsProperty class failed",
	MP4F_MP4UINTEGER64BITSPROPERTY_APPENDDUMP_FAILED,
		"The appendDump method of the MP4UInteger64BitsProperty class failed",

	// MP4Float16BitsProperty
	MP4F_MP4FLOAT16BITSPROPERTY_INIT_FAILED,
		"The init method of the MP4Float16BitsProperty class failed",
	MP4F_MP4FLOAT16BITSPROPERTY_GETSIZE_FAILED,
		"The getSize method of the MP4Float16BitsProperty class failed",
	MP4F_MP4FLOAT16BITSPROPERTY_WRITE_FAILED,
		"The write method of the MP4Float16BitsProperty class failed",
	MP4F_MP4FLOAT16BITSPROPERTY_PRINTONSTDOUTPUT_FAILED,
	"The printOnStdOutput method of the MP4Float16BitsProperty class failed",
	MP4F_MP4FLOAT16BITSPROPERTY_APPENDDUMP_FAILED,
		"The appendDump method of the MP4Float16BitsProperty class failed",

	// MP4Float32BitsProperty
	MP4F_MP4FLOAT32BITSPROPERTY_INIT_FAILED,
		"The init method of the MP4Float32BitsProperty class failed",
	MP4F_MP4FLOAT32BITSPROPERTY_GETSIZE_FAILED,
		"The getSize method of the MP4Float32BitsProperty class failed",
	MP4F_MP4FLOAT32BITSPROPERTY_WRITE_FAILED,
		"The write method of the MP4Float32BitsProperty class failed",
	MP4F_MP4FLOAT32BITSPROPERTY_PRINTONSTDOUTPUT_FAILED,
	"The printOnStdOutput method of the MP4Float32BitsProperty class failed",
	MP4F_MP4FLOAT32BITSPROPERTY_APPENDDUMP_FAILED,
		"The appendDump method of the MP4Float32BitsProperty class failed",

	// MP4StringNullTerminatedProperty
	MP4F_MP4STRINGNULLTERMINATEDPROPERTY_INIT_FAILED,
		"The init method of the MP4StringNullTerminatedProperty class failed",
	MP4F_MP4STRINGNULLTERMINATEDPROPERTY_GETSIZE_FAILED,
		"The getSize method of the MP4StringNullTerminatedProperty class failed",
	MP4F_MP4STRINGNULLTERMINATEDPROPERTY_WRITE_FAILED,
		"The write method of the MP4StringNullTerminatedProperty class failed",
	MP4F_MP4STRINGNULLTERMINATEDPROPERTY_PRINTONSTDOUTPUT_FAILED,
		"The printOnStdOutput method of the MP4StringNullTerminatedProperty class failed",
	MP4F_MP4STRINGNULLTERMINATEDPROPERTY_APPENDDUMP_FAILED,
		"The appendDump method of the MP4StringNullTerminatedProperty class failed",

	// MP4StringLastProperty
	MP4F_MP4STRINGLASTPROPERTY_INIT_FAILED,
		"The init method of the MP4StringLastProperty class failed",
	MP4F_MP4STRINGLASTPROPERTY_GETSIZE_FAILED,
		"The getSize method of the MP4StringLastProperty class failed",
	MP4F_MP4STRINGLASTPROPERTY_WRITE_FAILED,
		"The write method of the MP4StringLastProperty class failed",
	MP4F_MP4STRINGLASTPROPERTY_PRINTONSTDOUTPUT_FAILED,
		"The printOnStdOutput method of the MP4StringLastProperty class failed",
	MP4F_MP4STRINGLASTPROPERTY_APPENDDUMP_FAILED,
		"The appendDump method of the MP4StringLastProperty class failed",

	// MP4StringFixedProperty
	MP4F_MP4STRINGFIXEDPROPERTY_INIT_FAILED,
		"The init method of the MP4StringFixedProperty class failed",
	MP4F_MP4STRINGFIXEDPROPERTY_GETSIZE_FAILED,
		"The getSize method of the MP4StringFixedProperty class failed",
	MP4F_MP4STRINGFIXEDPROPERTY_WRITE_FAILED,
		"The write method of the MP4StringFixedProperty class failed",
	MP4F_MP4STRINGFIXEDPROPERTY_PRINTONSTDOUTPUT_FAILED,
	"The printOnStdOutput method of the MP4StringFixedProperty class failed",
	MP4F_MP4STRINGFIXEDPROPERTY_APPENDDUMP_FAILED,
		"The appendDump method of the MP4StringFixedProperty class failed",

	// MP4StringCountedProperty
	MP4F_MP4STRINGCOUNTEDPROPERTY_INIT_FAILED,
		"The init method of the MP4StringCountedProperty class failed",
	MP4F_MP4STRINGCOUNTEDPROPERTY_GETSIZE_FAILED,
		"The getSize method of the MP4StringCountedProperty class failed",
	MP4F_MP4STRINGCOUNTEDPROPERTY_WRITE_FAILED,
		"The write method of the MP4StringCountedProperty class failed",
	MP4F_MP4STRINGCOUNTEDPROPERTY_PRINTONSTDOUTPUT_FAILED,
	"The printOnStdOutput method of the MP4StringCountedProperty class failed",
	MP4F_MP4STRINGCOUNTEDPROPERTY_APPENDDUMP_FAILED,
		"The appendDump method of the MP4StringCountedProperty class failed",
	MP4F_MP4STRINGCOUNTEDPROPERTY_CHARSNUMBERWRONG,
		"Wrong chars number",

	// MP4BytesProperty
	MP4F_MP4BYTESPROPERTY_INIT_FAILED,
		"The init method of the MP4BytesProperty class failed",
	MP4F_MP4BYTESPROPERTY_GETSIZE_FAILED,
		"The getSize method of the MP4BytesProperty class failed",
	MP4F_MP4BYTESPROPERTY_WRITE_FAILED,
		"The write method of the MP4BytesProperty class failed",
	MP4F_MP4BYTESPROPERTY_PRINTONSTDOUTPUT_FAILED,
		"The printOnStdOutput method of the MP4BytesProperty class failed",
	MP4F_MP4BYTESPROPERTY_APPENDDUMP_FAILED,
		"The appendDump method of the MP4BytesProperty class failed",
	MP4F_MP4BYTESPROPERTY_GETDATA_FAILED,
		"The getData method of the MP4BytesProperty class failed",
	MP4F_MP4BYTESPROPERTY_GETPOINTERTODATA_FAILED,
		"The getPointerToData method of the MP4BytesProperty class failed",

	// MP4Atom
	MP4F_MP4ATOM_INIT_FAILED,
		"The init method of the MP4Atom class failed",
	MP4F_MP4ATOM_FINISH_FAILED,
		"The finish method of the MP4Atom class failed",
	MP4F_MP4ATOM_LOCKMP4FILE_FAILED,
		"The lockMP4File method of the MP4Atom class failed",
	MP4F_MP4ATOM_UNLOCKMP4FILE_FAILED,
		"The unLockMP4File method of the MP4Atom class failed",
	MP4F_MP4ATOM_APPENDDUMP_FAILED,
		"The appendDump method of the MP4Atom class failed",
	MP4F_MP4ATOM_APPENDPROPERTIESDUMP_FAILED,
		"The appendPropertiesDump method of the MP4Atom class failed",
	MP4F_MP4ATOM_PRINTONSTDOUTPUT_FAILED,
		"The printOnStdOutput method of the MP4Atom class failed",
	MP4F_MP4ATOM_PRINTPROPERTIESONSTDOUTPUT_FAILED,
		"The printPropertiesOnStdOutput method of the MP4Atom class failed",
	MP4F_MP4ATOM_PRINTPROPERTIESONSTDOUTPUT_FAILED,
		"The printPropertiesOnStdOutput method of the MP4Atom class failed",
	MP4F_MP4ATOM_PRINTPROPERTIESONSTDOUTPUT_FAILED,
		"The printPropertiesOnStdOutput method of the MP4Atom class failed",
	MP4F_MP4ATOM_WRITE_FAILED,
		"The write method of the MP4Atom class failed",
	MP4F_MP4ATOM_SEARCHATOM_FAILED,
		"The searchAtom method of the MP4Atom class failed (AtomPath: %s)",
	MP4F_MP4ATOM_ADDCHILD_FAILED,
		"The addChild method of the MP4Atom class failed",
	MP4F_MP4ATOM_DELETECHILD_FAILED,
		"The deleteChild method of the MP4Atom class failed",
	MP4F_MP4ATOM_GETPARENT_FAILED,
		"The getParent method of the MP4Atom class failed",
	MP4F_MP4ATOM_GETCHILD_FAILED,
		"The getChild method of the MP4Atom class failed",
	MP4F_MP4ATOM_GETPROPERTIESSIZE_FAILED,
		"The getPropertiesSize method of the MP4Atom class failed",
	MP4F_MP4ATOM_GETCHILDINDEX_FAILED,
		"The getChildIndex method of the MP4Atom class failed",
	MP4F_MP4ATOM_GETCHILDRENNUMBER_FAILED,
		"The getChildrenNumber method of the MP4Atom class failed",
	MP4F_MP4ATOM_GETSTARTOFFSET_FAILED,
		"The getStartOffset method of the MP4Atom class failed",
	MP4F_MP4ATOM_INCREMENTSTARTOFFSET_FAILED,
		"The incrementStartOffset method of the MP4Atom class failed",
	MP4F_MP4ATOM_CHANGESIZEMANAGEMENT_FAILED,
		"The changeSizeManagement method of the MP4Atom class failed",
	MP4F_MP4ATOM_GETSIZE_FAILED,
		"The getSize method of the MP4Atom class failed",
	MP4F_MP4ATOM_GETSTANDARD_FAILED,
		"The getStandard method of the MP4Atom class failed",
	MP4F_MP4ATOM_GETTYPE_FAILED,
		"The getType method of the MP4Atom class failed",
	MP4F_MP4ATOM_PREPARECHILDRENATOMSINFO_FAILED,
		"The prepareChildrenAtomsInfo method of the MP4Atom class failed",
	MP4F_MP4ATOM_CREATEPROPERTIES_FAILED,
		"The createProperties method of the MP4Atom class failed",
	MP4F_MP4ATOM_READPROPERTIES_FAILED,
		"The readProperties method of the MP4Atom class failed",
	MP4F_MP4ATOM_WRITEPROPERTIES_FAILED,
		"The writeProperties method of the MP4Atom class failed",
	MP4F_MP4ATOM_CREATECHILDATOMS_FAILED,
		"The createChildAtoms method of the MP4Atom class failed",
	MP4F_MP4ATOM_READCHILDATOMS_FAILED,
		"The readChildAtoms method of the MP4Atom class failed",
	MP4F_MP4ATOM_CONSISTENCYCHECK_FAILED,
		"The consistencyCheck method of the MP4Atom class failed",
	MP4F_MP4ATOM_BUILDATOM_FAILED,
		"The buildAtom method of the MP4Atom class failed",
	MP4F_MP4ATOM_BUILDDESCRIPTOR_FAILED,
		"The buildDescriptor method of the MP4Atom class failed",
	MP4F_MP4ATOM_ISDESCRIPTOR_FAILED,
		"The isDescriptor method of the MP4Atom class failed",
	MP4F_MP4ATOM_GETDESCRIPTORTAG_FAILED,
		"The getDescriptorTag method of the MP4Atom class failed",
	MP4F_MP4ATOM_ATOMTYPEUNKNOWN,
		"The '%s' Atom Type is unknown",
	MP4F_MP4ATOM_DESCRIPTORTYPEUNKNOWN,
		"The '%s' Descriptor Type is unknown",
	MP4F_MP4ATOM_DESCRIPTORTAGUNKNOWN,
		"The '%ld' Descriptor Tag is unknown",
	MP4F_MP4ATOM_TRACKTYPEUNKNOWN,
		"The '%s' track Type is unknown",
	MP4F_MP4ATOM_CODECUNKNOWN,
		"The codec of the track is unknown. Track id.: %lu",
	MP4F_MP4ATOM_PROPERTYNOTFOUND,
		"The '%s' property is not found",
	MP4F_MP4ATOM_ATOMNOTFOUND,
		"Atom not found (AtomPath: %s)",
	MP4F_MP4ATOM_WRONGATOMPARENT,
		"Wrong atom parent: %s",
	MP4F_MP4ATOM_ATOMINSTANCESNOTCORRECTED,
		"Instances number for '%s' atom is not corrected (Current Atoms Number: %ld)",
	MP4F_MP4ATOM_ATOMNOTINCORRECTPOSITION,
		"The '%s' atom is not in the corrected posistion within hierarchy (Parent type: '%s'",
	MP4F_MP4ATOM_ATOMMANDATORYNOTEXIST,
		"The '%s' atom is mandatory but doesn't exist (Parent: '%s')",

	// MP4CprtAtom
	MP4F_MP4CPRTATOM_SETNOTICE_FAILED,
		"The setNotice method of the MP4CprtAtom class failed",

	// MP4D263Atom
	MP4F_MP4D263ATOM_GETH263LEVEL_FAILED,
		"The method getH263Level of the MP4D263Atom class failed",
	MP4F_MP4D263ATOM_SETH263LEVEL_FAILED,
		"The method setH263Level of the MP4D263Atom class failed",
	MP4F_MP4D263ATOM_GETH263PROFILE_FAILED,
		"The method getH263Profile of the MP4D263Atom class failed",
	MP4F_MP4D263ATOM_SETH263PROFILE_FAILED,
		"The method setH263Profile of the MP4D263Atom class failed",

	// MP4FtypAtom
	MP4F_MP4FTYPATOM_GETMAJORBRAND_FAILED,
		"The getMajorBrand method of the MP4FtypAtom class failed",
	MP4F_MP4FTYPATOM_SETMAJORBRAND_FAILED,
		"The setMajorBrand method of the MP4FtypAtom class failed",
	MP4F_MP4FTYPATOM_GETMINORVERSION_FAILED,
		"The getMinorVersion method of the MP4FtypAtom class failed",
	MP4F_MP4FTYPATOM_SETMINORVERSION_FAILED,
		"The setMinorVersion method of the MP4FtypAtom class failed",
	MP4F_MP4FTYPATOM_GETCOMPATIBLEBRANDSCOUNT_FAILED,
		"The getCompatibleBrandsCount method of the MP4FtypAtom class failed",
	MP4F_MP4FTYPATOM_SETCOMPATIBLEBRANDSCOUNT_FAILED,
		"The setCompatibleBrandsCount method of the MP4FtypAtom class failed",
	MP4F_MP4FTYPATOM_GETBRAND_FAILED,
		"The getBrand method of the MP4FtypAtom class failed",
	MP4F_MP4FTYPATOM_SETBRAND_FAILED,
		"The setBrand method of the MP4FtypAtom class failed",

	// MP4HdlrAtom
	MP4F_MP4HDLRATOM_GETHANDLERTYPE_FAILED,
		"The getHandlerType method of the MP4HdlrAtom class failed",

	// MP4HintAtom
	MP4F_MP4HINTATOM_GETENTRIESNUMBER_FAILED,
		"The getEntriesNumber method of the MP4HintAtom class failed",
	MP4F_MP4HINTATOM_GETTRACKSREFERENCESTABLE_FAILED,
		"The getTracksReferencesTable method of the MP4HintAtom class failed",

	// MP4MdatAtom
	MP4F_MP4MDATATOM_GETPOINTERTODATA_FAILED,
		"The getPointerToData method of the MP4MdatAtom class failed",
	MP4F_MP4MDATATOM_GETDATASTARTOFFSET_FAILED,
		"The getDataStartOffset method of the MP4MdatAtom class failed",
	MP4F_MP4MDATATOM_APPENDDATA_FAILED,
		"The appendData method of the MP4MdatAtom class failed",
	MP4F_MP4MDATATOM_BYTESTOREADTOOBIG,
		"Bytes to read too big",

	// MP4MdhdAtom
	MP4F_MP4MDHDATOM_GETTIMESCALE_FAILED,
		"The getTimeScale method of the MP4MdhdAtom class failed",
	MP4F_MP4MDHDATOM_GETDURATION_FAILED,
		"The getDuration method of the MP4MdhdAtom class failed",

	// MP4Mp4vAtom
	MP4F_MP4MP4VATOM_GETWIDTH_FAILED,
		"The method getWidth of the MP4Mp4vAtom class failed",
	MP4F_MP4MP4VATOM_SETWIDTH_FAILED,
		"The method setWidth of the MP4Mp4vAtom class failed",
	MP4F_MP4MP4VATOM_GETHEIGHT_FAILED,
		"The method getHeight of the MP4Mp4vAtom class failed",
	MP4F_MP4MP4VATOM_SETHEIGHT_FAILED,
		"The method setHeight of the MP4Mp4vAtom class failed",

	// MP4MvhdAtom
	MP4F_MP4MVHDATOM_GETTIMESCALE_FAILED,
		"The getTimeScale method of the MP4MvhdAtom class failed",
	MP4F_MP4MVHDATOM_GETDURATION_FAILED,
		"The getDuration method of the MP4MvhdAtom class failed",

	// MP4NumpAtom
	MP4F_MP4NUMPATOM_GETPACKETS_FAILED,
		"The getPackets method of the MP4NumpAtom class failed",

	// MP4RootAtom
	MP4F_MP4ROOTATOM_MOVEMOOVATOMASLASTATOM_FAILED,
		"The moveMoovAtomAsLastAtom method of the MP4Atom class failed",
	MP4F_MP4ROOTATOM_MOOVATOMNOTFOUND,
		"In the 'root' atom it doesn't exist the 'moov' atom",

	// MP4RtpAtom
	MP4F_MP4RTPATOM_GETMAXPACKETSIZE_FAILED,
		"The getMaxPacketSize method of the MP4RtpAtom class failed",

	// MP4S263Atom
	MP4F_MP4S263ATOM_GETWIDTH_FAILED,
		"The method getWidth of the MP4S263Atom class failed",
	MP4F_MP4S263ATOM_SETWIDTH_FAILED,
		"The method setWidth of the MP4S263Atom class failed",
	MP4F_MP4S263ATOM_GETHEIGHT_FAILED,
		"The method getHeight of the MP4S263Atom class failed",
	MP4F_MP4S263ATOM_SETHEIGHT_FAILED,
		"The method setHeight of the MP4S263Atom class failed",

	// MP4SdpAtom
	MP4F_MP4SDPATOM_GETSDPTEXT_FAILED,
		"The method getSdpText of the MP4SdpAtom class failed",

	// MP4StcoAtom
	MP4F_MP4STCOATOM_GETCHUNKOFFSETTABLE_FAILED,
		"The method getChunkOffsetTable of the MP4StcoAtom class failed. Chunk number: %lu",

	// MP4StscAtom
	MP4F_MP4STSCATOM_GETSAMPLETOCHUNKTABLE_FAILED,
		"The method getSampleToChunkTable of the MP4StscAtom class failed. Index: %ld",

	// MP4StszAtom
	MP4F_MP4STSZATOM_GETSAMPLESNUMBER_FAILED,
		"The method getSamplesNumber of the MP4StszAtom class failed",

	// MP4TkhdAtom
	MP4F_MP4TKHDATOM_GETTRACKID_FAILED,
		"The method getTrackId of the MP4TkhdAtom class failed. Index: %ld",

	// MP4TimsAtom
	MP4F_MP4TIMSATOM_GETTIMESCALE_FAILED,
		"The getTimeScale method of the MP4TimsAtom class failed",

	// MP4UuidAtom
	MP4F_MP4UUIDATOM_GETEXTENDEDTYPE_FAILED,
		"The getExtendedType method of the MP4UuidAtom class failed",
	MP4F_MP4UUIDATOM_SETEXTENDEDTYPE_FAILED,
		"The setExtendedType method of the MP4UuidAtom class failed",
	MP4F_MP4UUIDATOM_SETDATA_FAILED,
		"The setData method of the MP4UuidAtom class failed",

	// MP4DecoderConfigDescr
	MP4F_MP4DECODERCONFIGDESCR_GETAVGBITRATE_FAILED,
		"The getAvgBitate method of the MP4DecoderConfigDescr class failed",

	// MP4Descr
	MP4F_MP4DESCR_GETTAG_FAILED,
		"The getTag method of the MP4Descr class failed",

	// MP4ESDescr
	MP4F_MP4ESDESCR_GETOCRSTREAMFLAG_FAILED,
		"The getOCRstreamFlag method of the MP4ESDescr class failed",

	// MP4InitialObjectDescr
	MP4F_MP4INITIALOBJECTDESCR_GETVISUALPROFILELEVELINDICATION_FAILED,
		"The getVisualProfileLevelIndication method of the MP4InitialObjectDescr class failed",
	MP4F_MP4INITIALOBJECTDESCR_SETVISUALPROFILELEVELINDICATION_FAILED,
		"The setVisualProfileLevelIndication method of the MP4InitialObjectDescr class failed",

	// MP4SyncLayerConfigDescr
	MP4F_MP4SYNCLAYERCONFIGDESCR_WRONGTIMESTAMPLENGTH,
	"The MP4SyncLayerConfigDescr descriptor contains a wrong TimeStampLength",

	// MP4File
	MP4F_MP4FILE_INIT_FAILED,
		"The init method of the MP4File class failed",
	MP4F_MP4FILE_FINISH_FAILED,
		"The finish method of the MP4File class failed",
	MP4F_MP4FILE_GETFILE_FAILED,
		"The getFile method of the MP4File class failed",
	MP4F_MP4FILE_GETDUMP_FAILED,
		"The getDump method of the MP4File class failed",
	MP4F_MP4FILE_INITIALIZETRACKSVECTOR_FAILED,
		"The initializeTracksInfo method of the MP4File class failed",
	MP4F_MP4FILE_GETTRACKSINFO_FAILED,
		"The getTracksInfo method of the MP4File class failed",
	MP4F_MP4FILE_GETFREEPAYLOADSNUMBER_FAILED,
		"The getFreePayloadsNumber method of the MP4File class failed",
	MP4F_MP4FILE_GETHINTTRAKFROMMEDIATRAKIDENTIFIER_FAILED,
	"The getHintTrakFromMediaTrakIdentifier method of the MP4File class failed",
	MP4F_MP4FILE_GETHINTTRACKINFOFROMMEDIATRACKINFO_FAILED,
	"The getHintTrackInfoFromMediaTrackInfo method of the MP4File class failed",
	MP4F_MP4FILE_GETMP4FILESTATUS_FAILED,
		"The getMP4FileStatus method of the MP4File class failed",
	MP4F_MP4FILE_GETMP4FILEPATH_FAILED,
		"The getMP4FilePath method of the MP4File class failed",
	MP4F_MP4FILE_GETROOTATOM_FAILED,
		"The getRootAtom method of the MP4File class failed",
	MP4F_MP4FILE_WRITE_FAILED,
		"The write method of the MP4File class failed (Track type: %s)",
	MP4F_MP4FILE_SEARCHATOM_FAILED,
		"The searchAtom method of the MP4File class failed (AtomPath: %s)",
	MP4F_MP4FILE_GETMOVIEDURATION_FAILED,
		"The getMovieDuration method of the MP4File class failed",
	MP4F_MP4FILE_GETTRAKINFOFROMIDENTIFIER_FAILED,
		"The getTrakInfoFromIdentifier method of the MP4File class failed",
	MP4F_MP4FILE_GETTRAKINFOFROMTRACKPOINTER_FAILED,
		"The getTrakInfoFromTrackPointer method of the MP4File class failed",
	MP4F_MP4FILE_GETSAMPLESNUMBER_FAILED,
		"The getSamplesNumber method of the MP4File class failed",
	MP4F_MP4FILE_GETPREVIOUSSYNCSAMPLE_FAILED,
		"The getPreviousSyncSample method of the MP4File class failed",
	MP4F_MP4FILE_SDPTEXTWRONG,
		"SDP text wrong. SDP: %s",
	MP4F_MP4FILE_NULLMAXMEDIASAMPLESIZE,
		"Null max media sample size",
	MP4F_MP4FILE_NULLTIMESCALE,
		"Null time scale",
	MP4F_MP4FILE_WRONGESCONFIGURATIONFOUND,
		"Wrong ES configuration found",
	MP4F_MP4FILE_ESCONFIGTOOLARGEFORRTPPAYLOAD,
		"ES configuration is too large for RTP payload",
	MP4F_MP4FILE_HINTTRACKNOTFOUND,
		"Hint track not found",
	MP4F_MP4FILE_VIDEOHINTTRACKNOTFOUND,
		"Video hint track not found",
	MP4F_MP4FILE_VIDEOTRACKNOTFOUND,
		"Video track not found",
	MP4F_MP4FILE_AUDIOHINTTRACKNOTFOUND,
		"Audio hint track not found",
	MP4F_MP4FILE_TRACKNOTRECONIZED_FAILED,
		"Track not reconized (track id.: %lu)",
	MP4F_MP4FILE_REQUESTEDSTOPTIMEREACHED,
		"Requested stop time reached",

	// MP4FileFactory
	MP4F_MP4FILEFACTORY_INIT_FAILED,
		"The init method of the MP4FileFactory class failed",
	MP4F_MP4FILEFACTORY_FINISH_FAILED,
		"The finish method of the MP4FileFactory class failed",
	MP4F_MP4FILEFACTORY_GETMP4FILE_FAILED,
		"The getMP4File method of the MP4FileFactory class failed",
	MP4F_MP4FILEFACTORY_ISMP4FILEINCACHE_FAILED,
		"The isMP4FileInCache method of the MP4FileFactory class failed",
	MP4F_MP4FILEFACTORY_RELEASEMP4FILE_FAILED,
		"The releaseMP4File method of the MP4FileFactory class failed",
	MP4F_MP4FILEFACTORY_MP4FILENOTFOUND,
		"MP4File not found (MP4File path: %s)",
	MP4F_MP4FILEFACTORY_RELEASEOFAFILENOREQUIRED,
		"Release of the '%s' file that it is no required",
	MP4F_MP4FILEFACTORY_REMOVEOLDERNOTUSEDMP4FILE_FAILED,
		"The removeOlderNotUsedMp4File method of the MP4FileFactory class failed",
	MP4F_MP4FILEFACTORY_FINDINDEXWHEREINSERT_FAILED,
		"The findIndexWhereInsert method of the MP4FileFactory class failed",
	MP4F_MP4FILEFACTORY_FILENOTFOUND,
		"The '%s' file is not found",

	// MP4Utility
	MP4F_MP4UTILITY_READFROMMDATATOM_FAILED,
		"The readFromMdatAtom method of the MP4Utility class failed",
	MP4F_MP4UTILITY_GETCHUNKOFFSETFROMCHUNKNUMBER_FAILED,
	"The getChunkOffsetFromChunkNumber method of the MP4Utility class failed",
	MP4F_MP4UTILITY_GETCHUNKFIRSTLASTSAMPLE_FAILED,
		"The getChunkFirstLastSample method of the MP4Utility class failed",
	MP4F_MP4UTILITY_GETPOINTERFROMMDATATOM_FAILED,
		"The getPointerFromMdatAtom method of the MP4Utility class failed",
	MP4F_MP4UTILITY_GETSAMPLESIZE_FAILED,
		"The getSampleSize method of the MP4Utility class failed",
	MP4F_MP4UTILITY_GETNEWTRACKIDENTIFIER_FAILED,
		"The getNewTrackIdentifier method of the MP4Utility class failed",
	MP4F_MP4UTILITY_NOPAYLOADAVAILABLE,
		"No more available rtp payload numbers",
	MP4F_MP4UTILITY_UPDATESAMPLESIZES_FAILED,
		"The updateSampleSizes method of the MP4Utility class failed",
	MP4F_MP4UTILITY_UPDATESAMPLETIMES_FAILED,
		"The updateSampleTimes method of the MP4Utility class failed",
	MP4F_MP4UTILITY_UPDATERENDERINGOFFSETS_FAILED,
		"The updateRenderingOffsets method of the MP4Utility class failed",
	MP4F_MP4UTILITY_UPDATESYNCSAMPLES_FAILED,
		"The updateSyncSamples method of the MP4Utility class failed",
	MP4F_MP4UTILITY_UPDATESAMPLETOCHUNK_FAILED,
		"The updateSampleToChunk method of the MP4Utility class failed",
	MP4F_MP4UTILITY_UPDATECHUNKOFFSET_FAILED,
		"The updateChunkOffset method of the MP4Utility class failed",
	MP4F_MP4UTILITY_UPDATEDURATIONS_FAILED,
		"The updateDurations method of the MP4Utility class failed",
	MP4F_MP4UTILITY_UPDATEMODIFICATIONSTIMES_FAILED,
		"The updateModificationsTimes method of the MP4Utility class failed",
	MP4F_MP4UTILITY_GETRENDERINGOFFSETFROMSAMPLENUMBER_FAILED,
		"The method getRenderingOffsetFromSampleNumber of the MP4Utility class failed. Sample identifier: %ld",
	MP4F_MP4UTILITY_ISSYNCSAMPLE_FAILED,
		"The method isSyncSample of the MP4Utility class failed. Sample identifier: %ld",
	MP4F_MP4UTILITY_GETPOINTERTRACKESCONFIGURATION_FAILED,
		"The getPointerTrackESConfiguration method of the MP4Utility class failed",
	MP4F_MP4UTILITY_GETMAXSAMPLESIZE_FAILED,
		"The getMaxSampleSize method of the MP4Utility class failed",
	MP4F_MP4UTILITY_GETPOINTERTOSAMPLE_FAILED,
		"The getPointerToSample method of the MP4Utility class failed",
	MP4F_MP4UTILITY_GETCODECNAME_FAILED,
		"The getCodecName method of the MP4Utility class failed",
	MP4F_MP4UTILITY_WRONGHANDLERTYPE,
		"The handler type field is wrong. (HandlerType: %s)",

	// MP4TrackInfo
	MP4F_MP4TRACKINFO_INIT_FAILED,
		"The init method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_FINISH_FAILED,
		"The finish method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETTRACKNAME_FAILED,
		"The getTrackName method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETHANDLERTYPE_FAILED,
		"The getHandlerType method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETCTTSATOM_FAILED,
		"The getCttsAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETAACAUDIODECODERCONFIGDESCR_FAILED,
		"The getAACAudioDecoderConfigDescr method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETMPEG4VIDEODECODERCONFIGDESCR_FAILED,
		"The getMPEG4VideoDecoderConfigDescr method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETD263ATOM_FAILED,
		"The getD263Atom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETDIMMATOM_FAILED,
		"The getDimmAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETDINFATOM_FAILED,
		"The getDinfAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETDMAXATOM_FAILED,
		"The getDmaxAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETDMEDATOM_FAILED,
		"The getDmedAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETDREFATOM_FAILED,
		"The getDrefAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETELSTATOM_FAILED,
		"The getElstAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETHDLRATOM_FAILED,
		"The getHdlrAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETHINFATOM_FAILED,
		"The getHinfAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETHINTATOM_FAILED,
		"The getHintAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETHMHDATOM_FAILED,
		"The getHmhdAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETMAXRATOM_FAILED,
		"The getMaxrAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETMDHDATOM_FAILED,
		"The getMdhdAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETMINFATOM_FAILED,
		"The getMinfAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETMP4VATOM_FAILED,
		"The getMp4vAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETNUMPATOM_FAILED,
		"The getNumpAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETPAYTATOM_FAILED,
		"The getPaytAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETPMAXATOM_FAILED,
		"The getPmaxAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETRTPATOM_FAILED,
		"The getRtpAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETS263ATOM_FAILED,
		"The getS263Atom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETSAMRATOM_FAILED,
		"The getSamrAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETSAWBATOM_FAILED,
		"The getSawbAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETSDPATOM_FAILED,
		"The getSdpAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETSNROATOM_FAILED,
		"The getSnroAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETSTBLATOM_FAILED,
		"The getStblAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETSTCOATOM_FAILED,
		"The getStcoAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETSTSCATOM_FAILED,
		"The getStscAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETSTSDATOM_FAILED,
		"The getStsdAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETSTSSATOM_FAILED,
		"The getStssAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETSTSZATOM_FAILED,
		"The getStszAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETSTTSATOM_FAILED,
		"The getSttsAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETTIMSATOM_FAILED,
		"The getTimsAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETTKHDATOM_FAILED,
		"The getTkhdAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETTPYLATOM_FAILED,
		"The getTpylAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETTRAKATOM_FAILED,
		"The getTrakAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETTRPYATOM_FAILED,
		"The getTrpyAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETTSROATOM_FAILED,
		"The getTsroAtom method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETMDHDTIMESCALE_FAILED,
		"The getMdhdTimeScale method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETTIMSTIMESCALE_FAILED,
		"The getTimsTimeScale method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETDURATION_FAILED,
		"The getDuration method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETSAMPLESNUMBER_FAILED,
		"The getSamplesNumber method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETMAXSAMPLESIZE_FAILED,
		"The getMaxSampleSize method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETAVGBITRATE_FAILED,
		"The getAvgBitRate method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETCODEC_FAILED,
		"The getCodec method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETPOINTERTRACKESCONFIGURATION_FAILED,
		"The getPointerTrackESConfiguration method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETTRACKIDENTIFIER_FAILED,
		"The getTrackIdentifier method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_GETOBJECTTYPEINDICATION_FAILED,
		"The getObjectTypeIndication method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_ADDHINTTRACK_FAILED,
		"The addHintTrack method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_DELETEHINTTRACK_FAILED,
		"The deleteHintTrack method of the MP4TrackInfo class failed",
	MP4F_MP4TRACKINFO_CODECNOTINITIALIZED,
		"Codec not initialized",
	MP4F_MP4TRACKINFO_OBJECTTYPEINDICATIONNOTINITIALIZED,
		"Object type indication not initialized",
	MP4F_MP4TRACKINFO_NOESCONFIGURATIONFOUND,
		"No ES configuration found",
	MP4F_MP4TRACKINFO_APPLIEDHINTTRACK,
		"Applied to hint track",


	// common
	MP4F_NEW_FAILED,
		"new failed",
	MP4F_GETTIMEOFDAY_FAILED,
		"gettimeodday failed",
	MP4F_ACTIVATION_WRONG,
		"Activation wrong",
	MP4F_NOTCONSISTENT,
		"Not consistent",
	MP4F_OPERATIONNOTALLOWED,
		"Operation not allowed (status: %ld)",
	MP4F_HASHMAP_ERROR,
		"Error on hash map",
	MP4F_NOTTESTED,
		"not implemented yet",
	MP4F_NOTIMPLEMENTEDYET,
		"not implemented yet"

	// Insert here other errors...

} ;

