/*
 Copyright (C) Giuliano Catrambone (giuliano.catrambone@catrasoftware.it)

 This program is free software; you can redistribute it and/or 
 modify it under the terms of the GNU General Public License 
 as published by the Free Software Foundation; either 
 version 2 of the License, or (at your option) any later 
 version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

 Commercial use other than under the terms of the GNU General Public
 License is allowed only after express negotiation of conditions
 with the authors.
*/


#ifndef RTPErrors_h
	#define RTPErrors_h

	#include "Error.h"
	#include <iostream>

	enum RTPErrorsCodes {

		// rfc...
		RTP_RFC_RFCISMAHINTER_FAILED,
		RTP_RFC_RFCISMAFRAGMENTER_FAILED,
		RTP_RFC_RFC3016VISUALHINTER_FAILED,
		RTP_RFC_RFC3016VISUALPREFETCHER_FAILED,
		RTP_RFC_RFC3016AUDIOHINTER_FAILED,
		RTP_RFC_RFC2429VISUALHINTER_FAILED,
		RTP_RFC_RFC2429VISUALPREFETCHER_FAILED,
		RTP_RFC_RFC3267AUDIOHINTER_FAILED,
		RTP_RFC_AUDIOINTERLEAVEHINTER_FAILED,
		RTP_RFC_RFC3016VISUALPREFETCHER_INSUFFICIENTRTPPACKETSNUMBER,
		RTP_RFC_RFC3016AUDIOPREFETCHER_INSUFFICIENTRTPPACKETSNUMBER,
		RTP_RFC_RFC2429VISUALPREFETCHER_INSUFFICIENTRTPPACKETSNUMBER,
		RTP_RFC_RTPPACKETNOTAVAILABLE,
		RTP_RFC_NOMEDIASAMPLES,
		RTP_RFC_NONAACAUDIOTYPE,
		RTP_RFC_INVALIDDURATION,
		RTP_RFC_TOOAMRFRAMESNUMBERINONEMDIASAMPLE,

		// RTPHintCreator
		RTP_RTPHINTCREATOR_INIT_FAILED,
		RTP_RTPHINTCREATOR_FINISH_FAILED,
		RTP_RTPHINTCREATOR_ADDRTPHINTSAMPLE_FAILED,
		RTP_RTPHINTCREATOR_ADDRTPHINTPACKETTOCURRENTRTPHINTSAMPLE_FAILED,
		RTP_RTPHINTCREATOR_ADDRTPREFERENCESAMPLETOCURRENTRTPHINTPACKET_FAILED,
		RTP_RTPHINTCREATOR_ADDRTPIMMEDIATEDATATOCURRENTRTPHINTPACKET_FAILED,
		RTP_RTPHINTCREATOR_UPDATESTATISTICSFORRTPHINTPACKET_FAILED,
		RTP_RTPHINTCREATOR_UPDATESTATISTICSFORRTPHINTSAMPLE_FAILED,
		RTP_RTPHINTCREATOR_APPENDRTPHINTSAMPLETOMDATATOM_FAILED,

		// RTPHintSample
		RTP_RTPHINTSAMPLE_INIT_FAILED,
		RTP_RTPHINTSAMPLE_FINISH_FAILED,
		RTP_RTPHINTSAMPLE_GETSTATE_FAILED,
		RTP_RTPHINTSAMPLE_CREATEPROPERTIES_FAILED,
		RTP_RTPHINTSAMPLE_GETPROPERTIES_FAILED,
		RTP_RTPHINTSAMPLE_CREATERTPHINTPACKET_FAILED,
		RTP_RTPHINTSAMPLE_APPENDTOMDATATOM_FAILED,
		RTP_RTPHINTSAMPLE_GETHINTSAMPLEIDENTIFIER_FAILED,
		RTP_RTPHINTSAMPLE_GETBYTESNUMBERFORMDAT_FAILED,
		RTP_RTPHINTSAMPLE_GETPACKETSNUMBER_FAILED,
		RTP_RTPHINTSAMPLE_GETHINTPACKET_FAILED,
		RTP_RTPHINTSAMPLE_NOTCONSISTENT,

		// RTPHintPacket
		RTP_RTPHINTPACKET_INIT_FAILED,
		RTP_RTPHINTPACKET_FINISH_FAILED,
		RTP_RTPHINTPACKET_CREATEPROPERTIES_FAILED,
		RTP_RTPHINTPACKET_GETPROPERTIES_FAILED,
		RTP_RTPHINTPACKET_GETRTPHINTPACKETDATA_FAILED,
		RTP_RTPHINTPACKET_GETRTPIMMEDIATEDATA_FAILED,
		RTP_RTPHINTPACKET_GETRTPREFERENCEDATA_FAILED,
		RTP_RTPHINTPACKET_GETENTRIESCOUNT_FAILED,
		RTP_RTPHINTPACKET_GETEXTRAINFORMATIONTVL_FAILED,
		RTP_RTPHINTPACKET_SETBFRAME_FAILED,
		RTP_RTPHINTPACKET_GETBFRAME_FAILED,
		RTP_RTPHINTPACKET_SETTLVTIMESTAMPOFFSET_FAILED,
		RTP_RTPHINTPACKET_GETTLVTIMESTAMPOFFSET_FAILED,
		RTP_RTPHINTPACKET_GETPAYLOADTYPE_FAILED,
		RTP_RTPHINTPACKET_SETPAYLOADTYPE_FAILED,
		RTP_RTPHINTPACKET_GETSEQUENCENUMBER_FAILED,
		RTP_RTPHINTPACKET_SETSEQUENCENUMBER_FAILED,
		RTP_RTPHINTPACKET_GETMARKERBIT_FAILED,
		RTP_RTPHINTPACKET_SETMARKERBIT_FAILED,
		RTP_RTPHINTPACKET_CREATERTPIMMEDIATEDATA_FAILED,
		RTP_RTPHINTPACKET_CREATERTPREFERENCESAMPLE_FAILED,
		RTP_RTPHINTPACKET_CREATEEMBEDDEDRTPREFERENCESAMPLE_FAILED,
		RTP_RTPHINTPACKET_GETBYTESNUMBERFORMDAT_FAILED,
		RTP_RTPHINTPACKET_GETPAYLOADANDPACKETPROPERTIESBYTESNUMBER_FAILED,
		RTP_RTPHINTPACKET_GETIMMEDIATEDATABYTESNUMBER_FAILED,
		RTP_RTPHINTPACKET_GETMEDIADATABYTESNUMBER_FAILED,
		RTP_RTPHINTPACKET_GETPAYLOADBYTESNUMBER_FAILED,
		RTP_RTPHINTPACKET_GETPACKET_FAILED,
		RTP_RTPHINTPACKET_GETRELATIVEPACKETTRANSMISSIONTIME_FAILED,
		RTP_RTPHINTPACKET_GETELEMENTSNUMBERINDATATABLE_FAILED,
		RTP_RTPHINTPACKET_GETHINTPACKETDATA_FAILED,
		RTP_RTPHINTPACKET_DATASOURCEWRONG,

		// RTPHintPacketData
		RTP_RTPHINTPACKETDATA_INIT_FAILED,
		RTP_RTPHINTPACKETDATA_FINISH_FAILED,
		RTP_RTPHINTPACKETDATA_CREATEPROPERTIES_FAILED,
		RTP_RTPHINTPACKETDATA_GETPACKETHINTDATA_FAILED,
		RTP_RTPHINTPACKETDATA_APPENDPAYLOADDATATORTPPACKET_FAILED,

		// RTPHintPacketImmediateData
		RTP_RTPHINTPACKETIMMEDIATEDATA_INIT_FAILED,
		RTP_RTPHINTPACKETIMMEDIATEDATA_FINISH_FAILED,
		RTP_RTPHINTPACKETIMMEDIATEDATA_SETDATA_FAILED,
		RTP_RTPHINTPACKETIMMEDIATEDATE_GETIMMEDIATELENGTH_FAILED,
		RTP_RTPHINTPACKETIMMEDIATEDATE_GETPAYLOADDATALENGTH_FAILED,
		RTP_RTPHINTPACKETIMMEDIATEDATA_BYTESNOTCONSISTENT,

		// RTPHintPacketSampleData
		RTP_RTPHINTPACKETSAMPLEDATA_INIT_FAILED,
		RTP_RTPHINTPACKETSAMPLEDATA_FINISH_FAILED,
		RTP_RTPHINTPACKETSAMPLEDATA_GETTRACKREFERENCEINDEX_FAILED,
		RTP_RTPHINTPACKETSAMPLEDATA_GETSAMPLELENGTH_FAILED,
		RTP_RTPHINTPACKETSAMPLEDATA_GETBYTESPERBLOCK_FAILED,
		RTP_RTPHINTPACKETSAMPLEDATA_GETSAMPLESPERBLOCK_FAILED,
		RTP_RTPHINTPACKETSAMPLEDATA_GETSAMPLEOFFSET_FAILED,
		RTP_RTPHINTPACKETSAMPLEDATA_SETREFERENCESAMPLE_FAILED,
		RTP_RTPHINTPACKETSAMPLEDATA_SETEMBEDDEDREFERENCESAMPLE_FAILED,
		RTP_RTPHINTPACKETSAMPLEDATA_APPENDPAYLOADDATATORTPPACKET_FAILED,
		RTP_RTPHINTPACKETSAMPLEDATA_WRONGTRACKREFERENCEINDEX,

		// RTPPacket
		RTP_RTPPACKET_INIT_FAILED,
		RTP_RTPPACKET_FINISH_FAILED,
		RTP_RTPPACKET_SETRTPPACKET_FAILED,
		RTP_RTPPACKET_SETRANDOMOFFSETS_FAILED,
		RTP_RTPPACKET_RESET_FAILED,
		RTP_RTPPACKET_SETVERSION_FAILED,
		RTP_RTPPACKET_GETMARKERBIT_FAILED,
		RTP_RTPPACKET_SETMARKERBIT_FAILED,
		RTP_RTPPACKET_GETTIMESTAMP_FAILED,
		RTP_RTPPACKET_SETTIMESTAMP_FAILED,
		RTP_RTPPACKET_GETSEQUENCENUMBER_FAILED,
		RTP_RTPPACKET_SETSEQUENCENUMBER_FAILED,
		RTP_RTPPACKET_GETPAYLOADTYPE_FAILED,
		RTP_RTPPACKET_SETPAYLOADTYPE_FAILED,
		RTP_RTPPACKET_SETSERVERSSRC_FAILED,
		RTP_RTPPACKET_APPENDDATA_FAILED,
		RTP_RTPPACKET_INSERTDATA_FAILED,
		RTP_RTPPACKET_DELETEDATA_FAILED,
		RTP_RTPPACKET_DATATOOBIGFORTHERTPPACKETSIZE,

		// RTPUtility
		RTP_RTPUTILITY_READSAMPLE_FAILED,
		RTP_RTPUTILITY_GETSAMPLENUMBERFROMSAMPLETIME_FAILED,
		RTP_RTPUTILITY_GETSAMPLETIMEFROMSAMPLENUMBER_FAILED,
		RTP_RTPUTILITY_APPENDHINTSAMPLETOMDATATOM_FAILED,
		RTP_RTPUTILITY_GETSAMPLEINFOFROMSAMPLENUMBER_FAILED,
		RTP_RTPUTILITY_GETCHUNKINFOFROMSAMPLENUMBER_FAILED,
		RTP_RTPUTILITY_GETSAMPLERANGESIZE_FAILED,
		RTP_RTPUTILITY_APPENDTORTPPACKETFROMMDATATOM_FAILED,
		RTP_RTPUTILITY_GETRTPTIMESCALE_FAILED,
		RTP_RTPUTILITY_GETAVGBITRATE_FAILED,
		RTP_RTPUTILITY_GETULONGRANDOM_FAILED,
		RTP_RTPUTILITY_GETUSHORTRANDOM_FAILED,
		RTP_RTPUTILITY_SAMPLESIZENOTCONSISTENT,
		RTP_RTPUTILITY_MEDIATIMETOOHIGH,
		RTP_RTPUTILITY_SAMPLEIDENTIFIERTOOHIGH,
		RTP_RTPUTILITY_CREATEHINTTRACK_FAILED,
		RTP_RTPUTILITY_CREATEALLHINTTRACKS_FAILED,
		RTP_RTPUTILITY_ALLOCRTPPAYLOADNUMBER_FAILED,

		// common
		RTP_NEW_FAILED,
		RTP_ACTIVATION_WRONG,
		RTP_NOTIMPLEMENTEDYET,

		// Insert here other errors...

		RTP_MAXERRORS
	} ;

	#ifdef WIN32
		// warning C4267: 'argument' : conversion from 'size_t' to 'long', possible loss of data

		#pragma warning (disable : 4267)
	#endif

	// declaration of class error
	dclCustomErrorClass (RTPErrors, RTP_MAXERRORS)
   
#endif

