/*
 Copyright (C) Giuliano Catrambone (giuliano.catrambone@catrasoftware.it)

 This program is free software; you can redistribute it and/or 
 modify it under the terms of the GNU General Public License 
 as published by the Free Software Foundation; either 
 version 2 of the License, or (at your option) any later 
 version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

 Commercial use other than under the terms of the GNU General Public
 License is allowed only after express negotiation of conditions
 with the authors.
*/


#ifndef SDPErrors_h
	#define SDPErrors_h

	#include "Error.h"
	#include <iostream>


	enum SDPErrorsCodes {

		// SDP
		SDP_SDP_INIT_FAILED,
		SDP_SDP_FINISH_FAILED,
		SDP_SDP_APPENDTOBUFFER_FAILED,
		SDP_SDP_ADDATTRIBUTE_FAILED,
		SDP_SDP_GETATTRIBUTEVALUE_FAILED,
		SDP_SDP_SETVERSION_FAILED,
		SDP_SDP_SETORIGINUSERNAME_FAILED,
		SDP_SDP_SETORIGINSESSIONID_FAILED,
		SDP_SDP_SETORIGINVERSION_FAILED,
		SDP_SDP_SETORIGINNETWORKTYPE_FAILED,
		SDP_SDP_SETORIGINADDRESSTYPE_FAILED,
		SDP_SDP_SETORIGINADDRESS_FAILED,
		SDP_SDP_SETSESSIONNAME_FAILED,
		SDP_SDP_SETINFORMATION_FAILED,
		SDP_SDP_SETURI_FAILED,
		SDP_SDP_SETEMAILADDRESS_FAILED,
		SDP_SDP_SETPHONENUMBER_FAILED,
		SDP_SDP_SETCONNECTIONNETWORKTYPE_FAILED,
		SDP_SDP_SETCONNECTIONADDRESSTYPE_FAILED,
		SDP_SDP_SETCONNECTIONADDRESS_FAILED,
		SDP_SDP_SETBANDWIDTHMODIFIER_FAILED,
		SDP_SDP_SETBANDWIDTHVALUEINKBPS_FAILED,
		SDP_SDP_SETTIMESSTART_FAILED,
		SDP_SDP_SETTIMESSTOP_FAILED,
		SDP_SDP_CREATEUNKNOWNSDPATTRIBUTE_FAILED,
		SDP_SDP_BUILDSDPMEDIA_FAILED,
		SDP_SDP_WRONGSTATEFORTHISLINE,
		SDP_SDP_FIELDTOOLONG,
		SDP_SDP_WRONGMEDIATYPE,
		SDP_SDP_SDPTYPENOTHANDLED,
		SDP_SDP_SDPMEDIANOTFOUND,
		SDP_SDP_ATTRIBUTEVALUEWRONG,
		SDP_SDP_ATTRIBUTENOTFOUND,

		// SDPForRTSP
		SDP_SDPFORRTSP_GETRANGEATTRIBUTEINFO_FAILED,
		SDP_SDPFORRTSP_INIT_FAILED,
		SDP_SDPFORRTSP_FINISH_FAILED,
		SDP_SDPFORRTSP_APPENDTOBUFFER_FAILED,
		SDP_SDPFORRTSP_GETSDPMEDIA_FAILED,

		// SDPFor3GPP
		SDP_SDPFOR3GPP_INIT_FAILED,
		SDP_SDPFOR3GPP_FINISH_FAILED,
		SDP_SDPFOR3GPP_GETATTRIBUTEVALUE_FAILED,
		SDP_SDPFOR3GPP_APPENDTOBUFFER_FAILED,
		SDP_SDPFOR3GPP_GETSDPMEDIA_FAILED,
		SDP_SDPFOR3GPP_ADDSDPMEDIA_FAILED,

		// SDPMedia
		SDP_SDPMEDIA_INIT_FAILED,
		SDP_SDPMEDIA_FINISH_FAILED,
		SDP_SDPMEDIA_APPENDTOBUFFER_FAILED,
		SDP_SDPMEDIA_GETMEDIAINFO_FAILED,
		SDP_SDPMEDIA_GETMEDIATYPE_FAILED,
		SDP_SDPMEDIA_SETMEDIATYPE_FAILED,
		SDP_SDP_ADDSDPMEDIA_FAILED,
		SDP_SDPMEDIA_SETPORT_FAILED,
		SDP_SDPMEDIA_SETTRANSPORT_FAILED,
		SDP_SDPMEDIA_GETFMTLIST_FAILED,
		SDP_SDPMEDIA_SETFMTLIST_FAILED,
		SDP_SDPMEDIA_SETINFORMATION_FAILED,
		SDP_SDPMEDIA_SETCONNECTIONNETWORKTYPE_FAILED,
		SDP_SDPMEDIA_SETCONNECTIONADDRESSTYPE_FAILED,
		SDP_SDPMEDIA_SETCONNECTIONADDRESS_FAILED,
		SDP_SDPMEDIA_SETBANDWIDTHMODIFIER_FAILED,
		SDP_SDPMEDIA_SETBANDWIDTHVALUEINKBPS_FAILED,
		SDP_SDPMEDIA_ADDATTRIBUTE_FAILED,
		SDP_SDPMEDIA_TRANSPORTTOOLONG,
		SDP_SDPMEDIA_FMTLISTTOOLONG,
		SDP_SDPMEDIA_INFORMATIONTOOLONG,
		SDP_SDPMEDIA_CONNECTIONNETWORKTYPETOOLONG,
		SDP_SDPMEDIA_CONNECTIONADDRESSTYPETOOLONG,
		SDP_SDPMEDIA_CONNECTIONADDRESSTOOLONG,
		SDP_SDPMEDIA_BANDWIDTHMODIFIERTOOLONG,
		SDP_SDPMEDIA_ATTRIBUTENOTFOUND,

		// SDPMediaFor3GPP
		SDP_SDPMEDIAFOR3GPP_APPENDTOBUFFER_FAILED,
		SDP_SDPMEDIAFOR3GPP_GETSDPMEDIAVIDEOFROMMEDIAINFO_FAILED,
		SDP_SDPMEDIAFOR3GPP_GETSDPMEDIAAUDIOFROMMEDIAINFO_FAILED,

		// SDPAttribute
		SDP_SDPATTRIBUTE_APPENDTOBUFFER_FAILED,

		// SDPTimeBase
		SDP_SDPTIMEBASE_INIT_FAILED,
		SDP_SDPTIMEBASE_FINISH_FAILED,
		SDP_SDPTIMEBASE_GETTIMEASNPT_FAILED,

		// SDPTimeNpt
		SDP_SDPTIMENPT_INIT_FAILED,
		SDP_SDPTIMENPT_FINISH_FAILED,

		// SDPTimeSmpte
		SDP_SDPTIMESMPTE_INIT_FAILED,
		SDP_SDPTIMESMPTE_FINISH_FAILED,

		// SDPTimeUtc
		SDP_SDPTIMEUTC_INIT_FAILED,
		SDP_SDPTIMEUTC_FINISH_FAILED,
		SDP_SDPTIMEUTC_WRONGUTCBUFFER,

		// common
		SDP_ACTIVATIONWRONG,
		SDP_NEW_FAILED,
		SDP_SSCANF_FAILED,

		// Insert here other errors...

		SDP_MAXERRORS
	} ;

	#ifdef WIN32
		// warning C4267: 'argument' : conversion from 'size_t' to 'long', possible loss of data

		#pragma warning (disable : 4267)
	#endif

	// declaration of class error
	dclCustomErrorClass (SDPErrors, SDP_MAXERRORS)
   
#endif

