/*
 Copyright (C) Giuliano Catrambone (giuliano.catrambone@catrasoftware.it)

 This program is free software; you can redistribute it and/or 
 modify it under the terms of the GNU General Public License 
 as published by the Free Software Foundation; either 
 version 2 of the License, or (at your option) any later 
 version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

 Commercial use other than under the terms of the GNU General Public
 License is allowed only after express negotiation of conditions
 with the authors.
*/


#ifndef StreamingServerErrors_h
	#define StreamingServerErrors_h

	#include "Error.h"
	#include <iostream>

	enum StreamingServerErrorsCodes {

		// catraStreamingServer
		SS_STREAMINGSERVERSMANAGER_IORFILEINSTEADNAMINGSERVER,
		SS_STARTTRACER_FAILED,
		SS_STOPTRACER_FAILED,
		SS_CHECKLICENSE_FAILED,
		SS_LICENSEEXPIRED,
		SS_LICENSECORRUPTED,
		SS_COREDUMP,

		// StreamingServer
		SS_STREAMINGSERVERSERVICE_ONINITMP4FILEFACTORY_FAILED,
		SS_STREAMINGSERVERSERVICE_ONINITRTSPSESSIONS_FAILED,
		SS_STREAMINGSERVER_INIT_FAILED,
		SS_STREAMINGSERVER_FINISH_FAILED,
		SS_STREAMINGSERVER_ADDRTSPSESSION_FAILED,
		SS_STREAMINGSERVER_DELETERTSPSESSION_FAILED,
		SS_STREAMINGSERVER_CANCEL_FAILED,
		SS_STREAMINGSERVER_SHUTDOWN_FAILED,
		SS_STREAMINGSERVER_ACTIVATE_FAILED,
		SS_STREAMINGSERVER_DEACTIVATE_FAILED,
		SS_STREAMINGSERVER_GETCONNECTEDUSERS_FAILED,
		SS_STREAMINGSERVER_GETCONNECTEDUSERSNUMBER_FAILED,
		SS_STREAMINGSERVER_GETSERVERCONNECTEDUSERS_FAILED,
		SS_STREAMINGSERVER_GETSERVERINFO_FAILED,
		SS_STREAMINGSERVER_ISREQUESTINCACHE_FAILED,
		SS_STREAMINGSERVER_SETISSHUTDOWN_FAILED,
		SS_STREAMINGSERVER_GETISSHUTDOWN_FAILED,
		SS_STREAMINGSERVER_INITNICS_FAILED,
		SS_STREAMINGSERVER_FINISHNICS_FAILED,
		SS_STREAMINGSERVER_REGISTERTONAMINGSERVICE_FAILED,
		SS_STREAMINGSERVER_DEREGISTERTONAMINGSERVICE_FAILED,
		SS_STREAMINGSERVER_NOTFOUNDRTSPSESSIONFREE,
		SS_STREAMINGSERVER_NAMINGCONTEXTNOTFOUND,
		SS_STREAMINGSERVER_NAMINGCONTEXTCANNOTPROCEED,
		SS_STREAMINGSERVER_NAMINGCONTEXTINVALIDNAME,
		SS_STREAMINGSERVER_NAMINGCONTEXTGENERICERROR,
		SS_STREAMINGSERVER_RTSPREQUESTINFOWRONG,
		SS_STREAMINGSERVER_WRONGHOSTNAME,
		SS_STREAMINGSERVER_UNKNOWNADDRESSTYPE,
		SS_STREAMINGSERVER_SHUTDOWNCORBAFAILED,
		SS_STREAMINGSERVER_LISTTOOLONG,
		SS_STREAMINGSERVER_RTCPRESERVEDPORTSNOTSUFFICIENT,

		// HttpStreamingServer
		SS_HTTPSTREAMINGSERVER_APPENDXMLFORCONNECTEDUSERS_FAILED,
		SS_HTTPSTREAMINGSERVER_APPENDXMLFORGETTRACKSINFO_FAILED,
		SS_HTTPSTREAMINGSERVER_APPENDXMLFORGETCONFIGURATION_FAILED,
		SS_HTTPSTREAMINGSERVER_APPENDXMLFORGETCONTENTS_FAILED,
		SS_HTTPSTREAMINGSERVER_WRONGHTTPREQUEST,

		// StreamingServerProcessor
		SS_STREAMINGSERVERPROCESSOR_INIT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_FINISH_FAILED,
		SS_STREAMINGSERVERPROCESSOR_CANCEL_FAILED,
		SS_STREAMINGSERVERPROCESSOR_SETISSHUTDOWN_FAILED,
		SS_STREAMINGSERVERPROCESSOR_GETISSHUTDOWN_FAILED,
		SS_STREAMINGSERVERPROCESSOR_PROCESSEVENT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_HANDLENEWRTSPCONNECTIONEVENT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_HANDLERTSPCONNECTIONREADYTOREADEVENT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_HANDLERTSP_RTCPTIMEOUTEVENT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_HANDLEPAUSETIMEOUTEVENT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_HANDLESTREAMINGSESSIONTIMEOUTEVENT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_HANDLERECEIVERTCPPACKETSEVENT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_HANDLESENDRTCPPACKETSEVENT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_HANDLESENDFILERTPPACKETSEVENT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_HANDLESENDLIVERTPPACKETSEVENT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_HANDLEAUTHORIZATIONERROREVENT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_HANDLEAUTHORIZATIONDENIEDEVENT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_HANDLEAUTHORIZATIONGRANTEDEVENT_FAILED,
		SS_STREAMINGSERVERPROCESSOR_CLOSECONNECTION_FAILED,
		SS_STREAMINGSERVERPROCESSOR_NOTFOUNDRTSPSESSIONFREE,
		SS_STREAMINGSERVERPROCESSOR_EVENTUNKNOWN,
		SS_STREAMINGSERVERPROCESSOR_LIVERTSPSESSIONNOTFOUND,
		SS_STREAMINGSERVERPROCESSOR_LIVERTSPSESSIONALREADYADDED,
		SS_STREAMINGSERVERPROCESSOR_RTSP_RTCPTIMEOUT,
		SS_STREAMINGSERVERPROCESSOR_PAUSETIMEOUT,
		SS_STREAMINGSERVERPROCESSOR_STREAMINGSESSIONTIMEOUT,
		SS_STREAMINGSERVERPROCESSOR_AUTHORIZATIONDENIED,
		SS_STREAMINGSERVERPROCESSOR_AUTHORIZATIONERROR,

		// RTSPConnectionEvent
		SS_RTSPCONNECTIONEVENT_INIT_FAILED,
		SS_RTSPCONNECTIONEVENT_FINISH_FAILED,
		SS_RTSPCONNECTIONEVENT_GETRTSPSESSIONIDENTIFIER_FAILED,
		SS_RTSPCONNECTIONEVENT_GETBUFFER_FAILED,
		SS_RTSPCONNECTIONEVENT_NEWRTSPCONNECTION,
		SS_RTSPCONNECTIONEVENT_BUFFERNOTINITIALIZED,

		// LiveEvent
		SS_LIVEEVENT_INIT_FAILED,
		SS_LIVEEVENT_FINISH_FAILED,
		SS_LIVEEVENT_GETLIVEEVENTINFO_FAILED,

		// LiveSource
		SS_LIVESOURCE_INIT_FAILED,
		SS_LIVESOURCE_FINISH_FAILED,
		SS_LIVESOURCE_ADDRTSPSESSION_FAILED,
		SS_LIVESOURCE_DELETERTSPSESSION_FAILED,
		SS_LIVESOURCE_ISINITIALIZED_FAILED,
		SS_LIVESOURCE_READRTPPACKET_FAILED,
		SS_LIVESOURCE_GETLASTRTPPACKET_FAILED,
		SS_LIVESOURCE_LIVERTSPSESSIONALREADYADDED,
		SS_LIVESOURCE_LIVERTSPSESSIONNOTFOUND,
		SS_LIVESOURCE_NOTHINGTOREAD,
		SS_LIVESOURCE_LASTRTPPACKETNOTFOUND,
		SS_LIVESOURCE_NOFOUNDFIRSTLIVERTPPACKETTOREAD,

		// StreamingServerEventsSet
		SS_STREAMINGSERVEREVENTSSET_MOVERTPPACKETTOVECTOR_FAILED,
		SS_STREAMINGSERVEREVENTSSET_GETRTPTIMESTAMPANDSEQUENCENUMBEROFFIRSTRTPPACKET_FAILED,
		SS_STREAMINGSERVEREVENTSSET_GETFREERTSPCONNECTIONEVENT_FAILED,
		SS_STREAMINGSERVEREVENTSSET_RELEASERTSPCONNECTIONEVENT_FAILED,
		SS_STREAMINGSERVEREVENTSSET_GETFREELIVEEVENT_FAILED,
		SS_STREAMINGSERVEREVENTSSET_RELEASELIVEEVENT_FAILED,
		SS_STREAMINGSERVEREVENTSSET_NORTPPACKETFOUND,
		SS_STREAMINGSERVEREVENTSSET_NOEVENTFREEFOUND,

		// CheckServerSocketTimes
		SS_CHECKSERVERSOCKETTIMES_INIT_FAILED,
		SS_CHECKSERVERSOCKETTIMES_FINISH_FAILED,

		// RTSP_RTCPTimes
		SS_RTSP_RTCPTIMES_INIT_FAILED,
		SS_RTSP_RTCPTIMES_FINISH_FAILED,

		// PauseTimes
		SS_PAUSETIMES_INIT_FAILED,
		SS_PAUSETIMES_FINISH_FAILED,

		// StreamingSessionTimes
		SS_STREAMINGSESSIONTIMES_INIT_FAILED,
		SS_STREAMINGSESSIONTIMES_FINISH_FAILED,

		// CheckReceivedRTCPPacketsTimes
		SS_CHECKRECEIVEDRTCPPACKETSTIMES_INIT_FAILED,
		SS_CHECKRECEIVEDRTCPPACKETSTIMES_FINISH_FAILED,

		// SendRTCPPacketsTimes
		SS_SENDRTCPPACKETSTIMES_INIT_FAILED,
		SS_SENDRTCPPACKETSTIMES_FINISH_FAILED,

		// RTPPacketsPrefetcherTimes
		SS_RTPPACKETSPREFETCHERTIMES_INIT_FAILED,
		SS_RTPPACKETSPREFETCHERTIMES_FINISH_FAILED,

		// CheckSocketsPoolTimes
		SS_CHECKSOCKETSPOOLTIMES_INIT_FAILED,
		SS_CHECKSOCKETSPOOLTIMES_FINISH_FAILED,

		// StreamingServerSocketsPool
		SS_STREAMINGSERVERSOCKETSPOOL_SOCKETIDENTIFIERWRONG,
		SS_STREAMINGSERVERSOCKETSPOOL_EXCEPTIONONSOCKET,

		// RTPPacketToSendEvent
		/*
		SS_RTPPACKETTOSENDEVENT_INIT_FAILED,
		SS_RTPPACKETTOSENDEVENT_FINISH_FAILED,
		SS_RTPPACKETTOSENDEVENT_GETRTSPSESSIONIDENTIFIER_FAILED,
		SS_RTPPACKETTOSENDEVENT_GETABSOLUTERTPPACHETTRANSMISSIONTIMEINMILLISECS_FAILED,
		SS_RTPPACKETTOSENDEVENT_GETTRACKIDENTIFIER_FAILED,
		SS_RTPPACKETTOSENDEVENT_GETRTPPACKET_FAILED,
		*/

		// StreamingServersManager
		/*
		SS_STREAMINGSERVERSMANAGER_ACTIVATESERVER_FAILED,
		SS_STREAMINGSERVERSMANAGER_DEACTIVATESERVER_FAILED,
		SS_STREAMINGSERVERSMANAGER_SHUTDOWNCORBAFAILED,
		SS_STREAMINGSERVERSMANAGER_WRONGHOSTNAME,
		SS_STREAMINGSERVERSMANAGER_UNKNOWNADDRESSTYPE,
		SS_STREAMINGSERVERSMANAGER_LISTTOOLONG,
		SS_STREAMINGSERVERSMANAGER_NOTFOUNDRTSPSESSIONFREE,
		SS_STREAMINGSERVERSMANAGER_NAMINGCONTEXTNOTFOUND,
		SS_STREAMINGSERVERSMANAGER_NAMINGCONTEXTCANNOTPROCEED,
		SS_STREAMINGSERVERSMANAGER_NAMINGCONTEXTINVALIDNAME,
		SS_STREAMINGSERVERSMANAGER_NAMINGCONTEXTGENERICERROR,
		SS_STREAMINGSERVERSMANAGER_STREAMINGSERVERERROR,
		*/

		// RTSPSessionRedirection
		SS_RTSPSESSIONREDIRECTION_CHOICESTREAMINGSERVERTOREDIRECT_FAILED,
		SS_RTSPSESSIONREDIRECTION_NOSTREAMINGSERVERAVAILABLE,

		// RTSPSession
		SS_RTSPSESSION_INIT_FAILED,
		SS_RTSPSESSION_FINISH_FAILED,
		SS_RTSPSESSION_GETRTSPSTATUS_FAILED,
		SS_RTSPSESSION_GETIDENTIFIER_FAILED,
		SS_RTSPSESSION_GETRTSP_RTCPTIMES_FAILED,
		SS_RTSPSESSION_GETPAUSETIMES_FAILED,
		SS_RTSPSESSION_GETCHECKRECEIVEDRTSPPACKETSTIMES_FAILED,
		SS_RTSPSESSION_GETSENDRTSPPACKETSTIMES_FAILED,
		SS_RTSPSESSION_ACCEPTRTSPCONNECTION_FAILED,
		SS_RTSPSESSION_ADDRTSPSESSIONFORTHELIVESOURCE_FAILED,
		SS_RTSPSESSION_DELETERTSPSESSIONFORTHELIVESOURCE_FAILED,
		SS_RTSPSESSION_SENDLIVERTPPACKET_FAILED,
		SS_RTSPSESSION_CLOSERTSPCONNECTION_FAILED,
		SS_RTSPSESSION_GETCLIENTSOCKET_FAILED,
		SS_RTSPSESSION_RESETTRACK_FAILED,
		SS_RTSPSESSION_ISLIVEREQUEST_FAILED,
		SS_RTSPSESSION_PARSEANDADJUSTLIVESDP_FAILED,
		SS_RTSPSESSION_ISLIVE_FAILED,
		SS_RTSPSESSION_GETLIVEINFO_FAILED,
		SS_RTSPSESSION_HANDLEDESCRIBEMETHOD_FAILED,
		SS_RTSPSESSION_HANDLEDESCRIBERESPONSE_FAILED,
		SS_RTSPSESSION_HANDLEANNOUNCEMETHOD_FAILED,
		SS_RTSPSESSION_HANDLEGET_PARAMETERMETHOD_FAILED,
		SS_RTSPSESSION_HANDLEOPTIONSMETHOD_FAILED,
		SS_RTSPSESSION_HANDLEPAUSEMETHOD_FAILED,
		SS_RTSPSESSION_HANDLEPLAYMETHOD_FAILED,
		SS_RTSPSESSION_HANDLERECORDMETHOD_FAILED,
		SS_RTSPSESSION_HANDLEREDIRECTMETHOD_FAILED,
		SS_RTSPSESSION_HANDLESETUPMETHOD_FAILED,
		SS_RTSPSESSION_HANDLESET_PARAMETERMETHOD_FAILED,
		SS_RTSPSESSION_HANDLETEARDOWNMETHOD_FAILED,
		SS_RTSPSESSION_SENDRTSPRESPONSE_FAILED,
		SS_RTSPSESSION_SEEK_FAILED,
		SS_RTSPSESSION_GETCURRENTPACKETRTPTIMESTAMPANDSEQUENCENUMBER_FAILED,
		SS_RTSPSESSION_GETSSRC_FAILED,
		SS_RTSPSESSION_GETANDREMOVENEXTRTPPACKETTOSEND_FAILED,
		SS_RTSPSESSION_PREFETCHNEXTPACKETS_FAILED,
		SS_RTSPSESSION_PREFETCHLIVEPACKET_FAILED,
		SS_RTSPSESSION_PREFETCHNEXTPACKETSUSINGHINTTRACK_FAILED,
		SS_RTSPSESSION_PREFETCHNEXTPACKETSUSINGMEDIATRACK_FAILED,
		SS_RTSPSESSION_ACTIVETRACK_FAILED,
		SS_RTSPSESSION_DEACTIVETRACK_FAILED,
		SS_RTSPSESSION_NOWINMILLISECONDS_FAILED,
		SS_RTSPSESSION_INITRTPSESSION_FAILED,
		SS_RTSPSESSION_FINISHRTPSESSION_FAILED,
		SS_RTSPSESSION_ADDTRACKTOSTREAM_FAILED,
		SS_RTSPSESSION_DELETETRACKTOSTREAM_FAILED,
		SS_RTSPSESSION_PROCESSRTSPREQUEST_FAILED,
		SS_RTSPSESSION_GETINFOFROMMP4FILE_FAILED,
		SS_RTSPSESSION_CHOICEMEDIATRACKSTOSTREAM_FAILED,
		SS_RTSPSESSION_GETPACKET_FAILED,
		SS_RTSPSESSION_SELECTTRACKOFNEXTPACKET_FAILED,
		SS_RTSPSESSION_SENDRTPPACKET_FAILED,
		SS_RTSPSESSION_SENDRTPPACKETS_FAILED,
		SS_RTSPSESSION_HANDLERECEIVERRTCPPACKETS_FAILED,
		SS_RTSPSESSION_HANDLESENDERRTCPPACKETS_FAILED,
		SS_RTSPSESSION_TRYTOREADANDPROCESSRTCPPACKETS_FAILED,
		SS_RTSPSESSION_SENDRTCPSRPACKET_FAILED,
		SS_RTSPSESSION_BUILDRTCPSRPACKET_FAILED,
		SS_RTSPSESSION_PROCESSRTCPPACKET_FAILED,
		SS_RTSPSESSION_PARSEURL_FAILED,
		SS_RTSPSESSION_PARSEURLPARAMETERS_FAILED,
		SS_RTSPSESSION_GETFINALINFO_FAILED,
		SS_RTSPSESSION_GETAVGBITRATE_FAILED,
		SS_RTSPSESSION_GETINFO_FAILED,
		SS_RTSPSESSION_GETAVERAGEBANDWIDTHUSAGE_FAILED,
		SS_RTSPSESSION_GETRANDOMOFFSETS_FAILED,
		SS_RTSPSESSION_GETVIDEOTRACKIDENTIFIER_FAILED,
		SS_RTSPSESSION_GETAUDIOTRACKIDENTIFIER_FAILED,
		SS_RTSPSESSION_GETREQUESTLOG_FAILED,
		SS_RTSPSESSION_RTCPMALFORMED,
		SS_RTSPSESSION_CODECSNOTSUPPORTED,
		SS_RTSPSESSION_NOMEDIATRACKS,
		SS_RTSPSESSION_TRACKNOTFOUND,
		SS_RTSPSESSION_UNKNOWNRTSPREQUEST,
		SS_RTSPSESSION_ATOMNOTEXIST,
		SS_RTSPSESSION_REFERENCETRACKNOTFOUND,
		SS_RTSPSESSION_RTSPCONNECTIONDOWN,
		SS_RTSPSESSION_DESCRIBEREQUESTWRONG,
		SS_RTSPSESSION_PLAYREQUESTWRONG,
		SS_RTSPSESSION_PAUSEREQUESTWRONG,
		SS_RTSPSESSION_TEARDOWNREQUESTWRONG,
		SS_RTSPSESSION_DESCRIBEURIWRONG,
		SS_RTSPSESSION_SETUPURIWRONGBECAUSETRACKNAME,
		SS_RTSPSESSION_SETUPURIWRONGBECAUSEFILENAME,
		SS_RTSPSESSION_PLAYTIMEWRONG,
		SS_RTSPSESSION_PORTSNOTAVAILABLE,
		SS_RTSPSESSION_TRACKSNOMOREAVAILABLE,
		SS_RTSPSESSION_TRACKNOTACTIVED,
		SS_RTSPSESSION_TRACKNOTINITIALIZED,
		SS_RTSPSESSION_SESSIONLOCKED,
		SS_RTSPSESSION_RTPFREEPACKETSVECTORNOTCONSISTENCY,
		SS_RTSPSESSION_TOOEARLYTOSENDTHEPACKET,
		SS_RTSPSESSION_NORTSPCONNECTIONTOACCEPT_FAILED,
		SS_RTSPSESSION_NOPACKETPREFETCHED,
		SS_RTSPSESSION_WRONGLIVESDP,
		SS_RTSPSESSION_TOOMANYLIVERTPPACKETS,
		SS_RTSPSESSION_NORTPPACKETFOUND,
		SS_RTSPSESSION_NOMORERTPPACKETS,
		SS_RTSPSESSION_NOPREFETCHEDRTPPACKET,
		SS_RTSPSESSION_URLPARAMETERWRONG,
		SS_RTSPSESSION_URLPARAMETERNOTAPPLICABLETOLIVE,
		SS_RTSPSESSION_URLPARAMETERUNKNOWN,
		SS_RTSPSESSION_TOOEARLYTOSENDRTCPPACKETS,
		SS_RTSPSESSION_TOOEARLYTORECEIVERTCPPACKETS,
		SS_RTSPSESSION_NOLIVERTSPSESSION,
		SS_RTSPSESSION_NOLIVESOURCEAVAILABLE,
		SS_RTSPSESSION_REQUESTEDPAYLOADSIZETOOBIG,
		SS_RTSPSESSION_STARTTIMEPARAMETERWRONG,
		SS_RTSPSESSION_REQUESTEDSTOPTIMEREACHED,
		SS_RTSPSESSION_NOTHINGTOREAD,

		// PacketsSender
		SS_PACKETSSENDER_INIT_FAILED,
		SS_PACKETSSENDER_FINISH_FAILED,
		SS_PACKETSSENDER_SETISSHUTDOWN_FAILED,
		SS_PACKETSSENDER_GETISSHUTDOWN_FAILED,
		SS_PACKETSSENDER_ADDRTSPSESSION_FAILED,
		SS_PACKETSSENDER_DELETERTSPSESSION_FAILED,
		SS_PACKETSSENDER_RTSPSESSIONNOTFOUND,

		// PacketsBuilder
		SS_PACKETSBUILDER_INIT_FAILED,
		SS_PACKETSBUILDER_FINISH_FAILED,
		SS_PACKETSBUILDER_SETISSHUTDOWN_FAILED,
		SS_PACKETSBUILDER_GETISSHUTDOWN_FAILED,
		SS_PACKETSBUILDER_ADDRTSPSESSION_FAILED,
		SS_PACKETSBUILDER_DELETERTSPSESSION_FAILED,
		SS_PACKETSBUILDER_RTSPSESSIONNOTFOUND,
		SS_PACKETSBUILDER_REACHEDMAXLIVESOURCESNUMBER,

		// RTPOverBufferWindow
		SS_RTPOVERBUFFERWINDOW_INIT_FAILED,
		SS_RTPOVERBUFFERWINDOW_FINISH_FAILED,
		SS_RTPOVERBUFFERWINDOW_ADDPACKETTOWINDOW_FAILED,
		SS_RTPOVERBUFFERWINDOW_EMPTYOUTWINDOW_FAILED,
		SS_RTPOVERBUFFERWINDOW_MARKBEGINNINGOFWRITEBURST_FAILED,
		SS_RTPOVERBUFFERWINDOW_RESETOVERBUFFERWINDOW_FAILED,
		SS_RTPOVERBUFFERWINDOW_PACKETBEFOREWINDOW,
		SS_RTPOVERBUFFERWINDOW_WINDOWVARIABLESNOTCONSISTENT,

		// BeginningHookHTTPGetThread
		SS_BEGINNINGHOOKHTTPGETTHREAD_INIT_FAILED,
		SS_BEGINNINGHOOKHTTPGETTHREAD_FINISH_FAILED,
		SS_BEGINNINGHOOKHTTPGETTHREAD_BEGINNINGHOOKHTTPGETRESPONSEWRONG,

		// windowsService
		SS_REPORTSTATUSTOSCMGR_FAILED,

		// common
		SS_ACTIVATION_WRONG,
		SS_ENVIRONMENTVARIABLE_NOTDEFINED,
		SS_RTSPSESSION_WRONGSTATE,
		SS_CORBA_GENERICERROR,
		SS_CONFIGITEMWRONG,
		SS_NEW_FAILED,
		SS_MKDIR_FAILED,
		SS_RMDIR_FAILED,
		SS_GETHOSTNAME_FAILED,
		SS_UNAME_FAILED,
		SS_UNLINK_FAILED,
		SS_OPEN_FAILED,
		SS_WRITE_FAILED,
		SS_CLOSE_FAILED,
		SS_LSTAT_FAILED,
		SS_SSCANF_FAILED,
		SS_FORK_FAILED,
		SS_CREATEPROCESS_FAILED,
		SS_LOCALTIME_R_FAILED,

		// Insert here other errors...

		SS_MAXERRORS
	} ;

	#ifdef WIN32
		// warning C4267: 'argument' : conversion from 'size_t' to 'long', possible loss of data

		#pragma warning (disable : 4267)
	#endif

	// declaration of class error
	dclCustomErrorClass (StreamingServerErrors, SS_MAXERRORS)
   
#endif

