/*
 Copyright (C) Giuliano Catrambone (giuliano.catrambone@catrasoftware.it)

 This program is free software; you can redistribute it and/or 
 modify it under the terms of the GNU General Public License 
 as published by the Free Software Foundation; either 
 version 2 of the License, or (at your option) any later 
 version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

 Commercial use other than under the terms of the GNU General Public
 License is allowed only after express negotiation of conditions
 with the authors.
*/


#include "StreamingServerErrors.h"



ErrMsgBase:: ErrMsgsInfo StreamingServerErrorsStr = {

	// catraStreamingServer
	SS_STREAMINGSERVERSMANAGER_IORFILEINSTEADNAMINGSERVER,
		"Use of the IOR file instead of Naming Service",
	SS_STARTTRACER_FAILED,
		"startTracer failed",
	SS_STOPTRACER_FAILED,
		"stopTracer failed",
	SS_CHECKLICENSE_FAILED,
		"checkLicense failed",
	SS_LICENSEEXPIRED,
		"License expired: %s",
	SS_LICENSECORRUPTED,
		"License corrupted: %s",
	SS_COREDUMP,
		"CORE DUMP. Received the signal: %lu",

	// StreamingServer
	SS_STREAMINGSERVERSERVICE_ONINITMP4FILEFACTORY_FAILED,
		"The method onInitMP4FileFactory of the StreamingServerService class failed",
	SS_STREAMINGSERVERSERVICE_ONINITRTSPSESSIONS_FAILED,
		"The method onInitRTSPSessions of the StreamingServerService class failed",
	SS_STREAMINGSERVER_INIT_FAILED,
		"The method init of the StreamingServer class failed",
	SS_STREAMINGSERVER_FINISH_FAILED,
		"The method finish of the StreamingServer class failed",
	SS_STREAMINGSERVER_ADDRTSPSESSION_FAILED,
		"The method addRTSPSession of the StreamingServer class failed",
	SS_STREAMINGSERVER_DELETERTSPSESSION_FAILED,
		"The method deleteRTSPSession of the StreamingServer class failed",
	SS_STREAMINGSERVER_CANCEL_FAILED,
		"The method cancel of the StreamingServer (no. %lu) class failed",
	SS_STREAMINGSERVER_SHUTDOWN_FAILED,
		"The method shutdown of the StreamingServer (no. %lu) class failed",
	SS_STREAMINGSERVER_ACTIVATE_FAILED,
		"The method activate of the StreamingServer class failed",
	SS_STREAMINGSERVER_DEACTIVATE_FAILED,
		"The method deactivate of the StreamingServer class failed",
	SS_STREAMINGSERVER_GETCONNECTEDUSERS_FAILED,
		"The method getConnectedUsers of the StreamingServer (no. %lu) class failed",
	SS_STREAMINGSERVER_GETCONNECTEDUSERSNUMBER_FAILED,
		"The method getConnectedUsersNumber of the StreamingServer (no. %lu) class failed",
	SS_STREAMINGSERVER_GETSERVERCONNECTEDUSERS_FAILED,
		"The method getServerConnectedUsers of the StreamingServer (no. %lu) class failed",
	SS_STREAMINGSERVER_GETSERVERINFO_FAILED,
		"The method getServerInfo of the StreamingServer (no. %lu) class failed",
	SS_STREAMINGSERVER_ISREQUESTINCACHE_FAILED,
		"The method isRequestInCache of the StreamingServer class failed",
	SS_STREAMINGSERVER_SETISSHUTDOWN_FAILED,
		"The method setIsShutdown of the StreamingServer class failed",
	SS_STREAMINGSERVER_GETISSHUTDOWN_FAILED,
		"The method getIsShutdown of the StreamingServer class failed",
	SS_STREAMINGSERVER_INITNICS_FAILED,
		"The method initNICS of the StreamingServer class failed",
	SS_STREAMINGSERVER_FINISHNICS_FAILED,
		"The method finishNICS of the StreamingServer class failed",
	SS_STREAMINGSERVER_REGISTERTONAMINGSERVICE_FAILED,
		"The method registerToNamingService of the StreamingServer class failed",
	SS_STREAMINGSERVER_DEREGISTERTONAMINGSERVICE_FAILED,
		"The method deRegisterToNamingService of the StreamingServer class failed",
	SS_STREAMINGSERVER_NOTFOUNDRTSPSESSIONFREE,
		"Not found RTSP sessions free",
	SS_STREAMINGSERVER_NAMINGCONTEXTNOTFOUND,
		"Naming Service: naming context not found",
	SS_STREAMINGSERVER_NAMINGCONTEXTCANNOTPROCEED,
		"Naming Service: naming context cannot proceed",
	SS_STREAMINGSERVER_NAMINGCONTEXTINVALIDNAME,
		"Naming Service: naming context invalid name",
	SS_STREAMINGSERVER_NAMINGCONTEXTGENERICERROR,
		"Naming Service: generic error",
	SS_STREAMINGSERVER_RTSPREQUESTINFOWRONG,
		"RTSP request info wrong",
	SS_STREAMINGSERVER_WRONGHOSTNAME,
		"Wrong host name. Host name: %s",
	SS_STREAMINGSERVER_UNKNOWNADDRESSTYPE,
		"Unknown address type. Address type: %ld",
	SS_STREAMINGSERVER_SHUTDOWNCORBAFAILED,
		"Shutdown CORBA failed",
	SS_STREAMINGSERVER_LISTTOOLONG,
		"List too long",
	SS_STREAMINGSERVER_RTCPRESERVEDPORTSNOTSUFFICIENT,
		"%lu reserved sockets ports are not sufficient to handle %lu RTSP sessions. Increase the 'RTP_RTCPReservedPorts' conf. parameter or decrease the 'MaxRTSPServerSessions' conf. parameter",

	// HttpStreamingServer
	SS_HTTPSTREAMINGSERVER_APPENDXMLFORCONNECTEDUSERS_FAILED,
	"The appendXMLForConnectedUsers of the HttpStreamingServer class failed",
	SS_HTTPSTREAMINGSERVER_APPENDXMLFORGETTRACKSINFO_FAILED,
	"The appendXMLForGetTracksInfo of the HttpStreamingServer class failed",
	SS_HTTPSTREAMINGSERVER_APPENDXMLFORGETCONFIGURATION_FAILED,
	"The appendXMLForGetConfiguration of the HttpStreamingServer class failed",
	SS_HTTPSTREAMINGSERVER_APPENDXMLFORGETCONTENTS_FAILED,
	"The appendXMLForGetContents of the HttpStreamingServer class failed",
	SS_HTTPSTREAMINGSERVER_WRONGHTTPREQUEST,
		"Wrong HTTP request. HTTP request: %s",

	// StreamingServerProcessor
	SS_STREAMINGSERVERPROCESSOR_INIT_FAILED,
		"The method init of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_FINISH_FAILED,
		"The method finish of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_CANCEL_FAILED,
		"The method cancel of the StreamingServerProcessor (no. %lu) class failed",
	SS_STREAMINGSERVERPROCESSOR_SETISSHUTDOWN_FAILED,
		"The method setIsShutdown of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_GETISSHUTDOWN_FAILED,
		"The method getIsShutdown of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_PROCESSEVENT_FAILED,
		"The method processEvent of the StreamingServerProcessor (no. %lu) class failed",
	SS_STREAMINGSERVERPROCESSOR_HANDLENEWRTSPCONNECTIONEVENT_FAILED,
		"The method handleNewRTSPConnectionEvent of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_HANDLERTSPCONNECTIONREADYTOREADEVENT_FAILED,
		"The method handleRTSPConnectionReadyToReadEvent of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_HANDLERTSP_RTCPTIMEOUTEVENT_FAILED,
		"The method handleRTSP_RTCPTimeoutEvent of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_HANDLEPAUSETIMEOUTEVENT_FAILED,
		"The method handlePauseTimeoutEvent of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_HANDLESTREAMINGSESSIONTIMEOUTEVENT_FAILED,
		"The method handleStreamingSessionTimeoutEvent of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_HANDLERECEIVERTCPPACKETSEVENT_FAILED,
		"The method handleReceiveRTCPPacketsEvent of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_HANDLESENDRTCPPACKETSEVENT_FAILED,
		"The method handleSendRTCPPacketsEvent of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_HANDLESENDFILERTPPACKETSEVENT_FAILED,
		"The method handleSendFileRTPPacketsEvent of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_HANDLESENDLIVERTPPACKETSEVENT_FAILED,
		"The method handleSendLiveRTPPacketsEvent of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_HANDLEAUTHORIZATIONERROREVENT_FAILED,
		"The method handleAuthorizationErrorEvent of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_HANDLEAUTHORIZATIONDENIEDEVENT_FAILED,
		"The method handleAuthorizationDeniedEvent of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_HANDLEAUTHORIZATIONGRANTEDEVENT_FAILED,
		"The method handleAuthorizationGrantedEvent of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_CLOSECONNECTION_FAILED,
		"The method closeConnection of the StreamingServerProcessor class failed",
	SS_STREAMINGSERVERPROCESSOR_NOTFOUNDRTSPSESSIONFREE,
		"Not found RTSP session free",
	SS_STREAMINGSERVERPROCESSOR_EVENTUNKNOWN,
		"Event unknown (Type identifier: %lu)",
	SS_STREAMINGSERVERPROCESSOR_LIVERTSPSESSIONNOTFOUND,
		"Live RTSP session not found",
	SS_STREAMINGSERVERPROCESSOR_LIVERTSPSESSIONALREADYADDED,
		"Live RTSP session already added",
	SS_STREAMINGSERVERPROCESSOR_RTSP_RTCPTIMEOUT,
		"RTSPSession identifier: %lu. RTSP RTCP timeout",
	SS_STREAMINGSERVERPROCESSOR_PAUSETIMEOUT,
		"RTSPSession identifier: %lu. Pause timeout",
	SS_STREAMINGSERVERPROCESSOR_STREAMINGSESSIONTIMEOUT,
		"RTSPSession identifier: %lu. Streaming session timeout",
	SS_STREAMINGSERVERPROCESSOR_AUTHORIZATIONDENIED,
		"RTSPSession identifier: %lu. Authorization denied: %s",
	SS_STREAMINGSERVERPROCESSOR_AUTHORIZATIONERROR,
		"RTSPSession identifier: %lu. Authorization error: %s",

	// RTSPConnectionEvent
	SS_RTSPCONNECTIONEVENT_INIT_FAILED,
		"The method init of the RTSPConnectionEvent class failed",
	SS_RTSPCONNECTIONEVENT_FINISH_FAILED,
		"The method finish of the RTSPConnectionEvent class failed",
	SS_RTSPCONNECTIONEVENT_GETRTSPSESSIONIDENTIFIER_FAILED,
		"The method getRTSPSessionIdentifier of the RTSPConnectionEvent class failed",
	SS_RTSPCONNECTIONEVENT_GETBUFFER_FAILED,
		"The method getBuffer of the RTSPConnectionEvent class failed",
	SS_RTSPCONNECTIONEVENT_NEWRTSPCONNECTION,
		"No RTSP connection identifier because it's a new RTSP connection",
	SS_RTSPCONNECTIONEVENT_BUFFERNOTINITIALIZED,
		"Buffer not initialized",

	// LiveEvent
	SS_LIVEEVENT_INIT_FAILED,
		"The method init of the LiveEvent class failed",
	SS_LIVEEVENT_FINISH_FAILED,
		"The method finish of the LiveEvent class failed",
	SS_LIVEEVENT_GETLIVEEVENTINFO_FAILED,
		"The method getLiveEventInfo of the LiveEvent class failed",

	// LiveSource
	SS_LIVESOURCE_INIT_FAILED,
		"The method init of the LiveEvent class failed",
	SS_LIVESOURCE_FINISH_FAILED,
		"The method finish of the LiveEvent class failed",
	SS_LIVESOURCE_ADDRTSPSESSION_FAILED,
		"The method addRTSPSession of the LiveEvent class failed",
	SS_LIVESOURCE_DELETERTSPSESSION_FAILED,
		"The method deleteRTSPSession of the LiveEvent class failed",
	SS_LIVESOURCE_ISINITIALIZED_FAILED,
		"The method isInitialized of the LiveEvent class failed",
	SS_LIVESOURCE_READRTPPACKET_FAILED,
		"The method readRTPPacket of the LiveEvent class failed",
	SS_LIVESOURCE_GETLASTRTPPACKET_FAILED,
		"The method getLastRTPPacket of the LiveEvent class failed",
	SS_LIVESOURCE_LIVERTSPSESSIONALREADYADDED,
		"Live RTSP session already added",
	SS_LIVESOURCE_LIVERTSPSESSIONNOTFOUND,
		"Live RTSP session not found",
	SS_LIVESOURCE_NOTHINGTOREAD,
		"Nothing to read",
	SS_LIVESOURCE_LASTRTPPACKETNOTFOUND,
		"Last RTP Packet not found",
	SS_LIVESOURCE_NOFOUNDFIRSTLIVERTPPACKETTOREAD,
		"RTSPSession identifier: %lu. No found the first %s RTP packet to read, timeout used: %lu seconds",

	// StreamingServerEventsSet
	SS_STREAMINGSERVEREVENTSSET_MOVERTPPACKETTOVECTOR_FAILED,
		"The method moveRTPPacketToVector of the StreamingServerEventsSet class failed",
	SS_STREAMINGSERVEREVENTSSET_GETRTPTIMESTAMPANDSEQUENCENUMBEROFFIRSTRTPPACKET_FAILED,
		"The method getRTPTimeStampAndSequenceNumberOfFirstRTPPacket of the StreamingServerEventsSet class failed",
	SS_STREAMINGSERVEREVENTSSET_GETFREERTSPCONNECTIONEVENT_FAILED,
	"The method getFreeRTSPConnectionEvent of the StreamingServerEventsSet class failed. Event not enqueued: %s",
	SS_STREAMINGSERVEREVENTSSET_RELEASERTSPCONNECTIONEVENT_FAILED,
		"The method releaseRTSPConnectionEvent of the StreamingServerEventsSet class failed",
	SS_STREAMINGSERVEREVENTSSET_GETFREELIVEEVENT_FAILED,
		"The method getFreeLiveEvent of the StreamingServerEventsSet class failed",
	SS_STREAMINGSERVEREVENTSSET_RELEASELIVEEVENT_FAILED,
		"The method releaseLiveEvent of the StreamingServerEventsSet class failed",
	SS_STREAMINGSERVEREVENTSSET_NORTPPACKETFOUND,
		"No RTPPacket found for RTSP session (%lu) and Track identifier (%lu)",
	SS_STREAMINGSERVEREVENTSSET_NOEVENTFREEFOUND,
		"No Event free found",

	// CheckServerSocketTimes
	SS_CHECKSERVERSOCKETTIMES_INIT_FAILED,
		"The method init of the CheckServerSocketTimes class failed",
	SS_CHECKSERVERSOCKETTIMES_FINISH_FAILED,
		"The method finish of the CheckServerSocketTimes class failed",

	// RTSP_RTCPTimes
	SS_RTSP_RTCPTIMES_INIT_FAILED,
		"The method init of the RTSP_RTCPTimes class failed",
	SS_RTSP_RTCPTIMES_FINISH_FAILED,
		"The method finish of the RTSP_RTCPTimes class failed",

	// PauseTimes
	SS_PAUSETIMES_INIT_FAILED,
		"The method init of the PauseTimes class failed",
	SS_PAUSETIMES_FINISH_FAILED,
		"The method finish of the PauseTimes class failed",

	// StreamingSessionTimes
	SS_STREAMINGSESSIONTIMES_INIT_FAILED,
		"The method init of the StreamingSessionTimes class failed",
	SS_STREAMINGSESSIONTIMES_FINISH_FAILED,
		"The method finish of the StreamingSessionTimes class failed",

	// CheckReceivedRTCPPacketsTimes
	SS_CHECKRECEIVEDRTCPPACKETSTIMES_INIT_FAILED,
		"The method init of the CheckReceivedRTCPPacketsTimes class failed",
	SS_CHECKRECEIVEDRTCPPACKETSTIMES_FINISH_FAILED,
		"The method finish of the CheckReceivedRTCPPacketsTimes class failed",

	// SendRTCPPacketsTimes
	SS_SENDRTCPPACKETSTIMES_INIT_FAILED,
		"The method init of the SendRTCPPacketsTimes class failed",
	SS_SENDRTCPPACKETSTIMES_FINISH_FAILED,
		"The method finish of the SendRTCPPacketsTimes class failed",

	// RTPPacketsPrefetcherTimes
	SS_RTPPACKETSPREFETCHERTIMES_INIT_FAILED,
		"The method init of the RTPPacketsPrefetcherTimes class failed",
	SS_RTPPACKETSPREFETCHERTIMES_FINISH_FAILED,
		"The method finish of the RTPPacketsPrefetcherTimes class failed",

	// CheckSocketsPoolTimes
	SS_CHECKSOCKETSPOOLTIMES_INIT_FAILED,
		"The method init of the CheckSocketsPoolTimes class failed",
	SS_CHECKSOCKETSPOOLTIMES_FINISH_FAILED,
		"The method finish of the CheckSocketsPoolTimes class failed",

	// StreamingServerSocketsPool
	SS_STREAMINGSERVERSOCKETSPOOL_SOCKETIDENTIFIERWRONG,
		"Socket identifier wrong (%ld)",
	SS_STREAMINGSERVERSOCKETSPOOL_EXCEPTIONONSOCKET,
		"RTSPSession identifier: %lu. Exception of the Socket, identifier: %ld",

	// StreamingServersManager
	/*
	SS_STREAMINGSERVERSMANAGER_NOTFOUNDRTSPSESSIONFREE,
		"Not found RTSP sessions free",
	SS_STREAMINGSERVERSMANAGER_NAMINGCONTEXTNOTFOUND,
		"Naming Service: naming context not found",
	SS_STREAMINGSERVERSMANAGER_NAMINGCONTEXTCANNOTPROCEED,
		"Naming Service: naming context cannot proceed",
	SS_STREAMINGSERVERSMANAGER_NAMINGCONTEXTINVALIDNAME,
		"Naming Service: naming context invalid name",
	SS_STREAMINGSERVERSMANAGER_NAMINGCONTEXTGENERICERROR,
		"Naming Service: generic error. Name service: %s",
	SS_STREAMINGSERVERSMANAGER_STREAMINGSERVERERROR,
		"CORBA streaming server error. Method: %s",
	*/

	// RTSPSessionRedirection
	SS_RTSPSESSIONREDIRECTION_CHOICESTREAMINGSERVERTOREDIRECT_FAILED,
		"The method choiceStreamingServerToRedirect of the RTSPSessionRedirection class failed",
	SS_RTSPSESSIONREDIRECTION_NOSTREAMINGSERVERAVAILABLE,
		"No streaming server available",

	// RTSPSession
	SS_RTSPSESSION_INIT_FAILED,
		"The method init of the RTSPSession class failed",
	SS_RTSPSESSION_FINISH_FAILED,
		"The method finish of the RTSPSession class failed",
	SS_RTSPSESSION_GETRTSPSTATUS_FAILED,
		"The method getRTSPStatus of the RTSPSession class failed",
	SS_RTSPSESSION_GETIDENTIFIER_FAILED,
		"The method getIdentifier of the RTSPSession class failed",
	SS_RTSPSESSION_GETRTSP_RTCPTIMES_FAILED,
		"The method getRTSP_RTCPTimes of the RTSPSession class failed",
	SS_RTSPSESSION_GETPAUSETIMES_FAILED,
		"The method getPauseTimes of the RTSPSession class failed",
	SS_RTSPSESSION_GETCHECKRECEIVEDRTSPPACKETSTIMES_FAILED,
		"The method getCheckReceivedRTCPPacketsTimes of the RTSPSession class failed",
	SS_RTSPSESSION_GETSENDRTSPPACKETSTIMES_FAILED,
		"The method getSendRTCPPacketsTimes of the RTSPSession class failed",
	SS_RTSPSESSION_ACCEPTRTSPCONNECTION_FAILED,
		"The method acceptRTSPConnection of the RTSPSession class failed",
	SS_RTSPSESSION_ADDRTSPSESSIONFORTHELIVESOURCE_FAILED,
		"The method addRTSPSessionForTheLiveSource of the RTSPSession class failed",
	SS_RTSPSESSION_DELETERTSPSESSIONFORTHELIVESOURCE_FAILED,
		"The method deleteRTSPSessionForTheLiveSource of the RTSPSession class failed",
	SS_RTSPSESSION_SENDLIVERTPPACKET_FAILED,
		"The method sendLiveRTPPacket of the RTSPSession class failed",
	SS_RTSPSESSION_CLOSERTSPCONNECTION_FAILED,
		"The method closeRTSPConnection of the RTSPSession class failed",
	SS_RTSPSESSION_GETCLIENTSOCKET_FAILED,
		"The method getClientSocket of the RTSPSession class failed",
	SS_RTSPSESSION_RESETTRACK_FAILED,
		"The method resetTrack of the RTSPSession class failed",
	SS_RTSPSESSION_ISLIVEREQUEST_FAILED,
		"The method isLiveRequest of the RTSPSession class failed",
	SS_RTSPSESSION_PARSEANDADJUSTLIVESDP_FAILED,
		"The method parseAndAdjustLiveSDP of the RTSPSession class failed",
	SS_RTSPSESSION_ISLIVE_FAILED,
		"The method isLive of the RTSPSession class failed",
	SS_RTSPSESSION_GETLIVEINFO_FAILED,
		"The method getLiveInfo of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLEDESCRIBEMETHOD_FAILED,
		"The method handleDESCRIBEMethod of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLEDESCRIBERESPONSE_FAILED,
		"The method handleDESCRIBEResponse of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLEANNOUNCEMETHOD_FAILED,
		"The method handleANNOUNCEMethod of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLEGET_PARAMETERMETHOD_FAILED,
		"The method handleGET_PARAMETERMethod of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLEOPTIONSMETHOD_FAILED,
		"The method handleOPTIONSMethod of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLEPAUSEMETHOD_FAILED,
		"RTSPSession identifier: %lu. The method handlePAUSEMethod of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLEPLAYMETHOD_FAILED,
		"The method handlePLAYMethod of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLERECORDMETHOD_FAILED,
		"The method handleRECORDMethod of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLEREDIRECTMETHOD_FAILED,
		"The method handleREDIRECTMethod of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLESETUPMETHOD_FAILED,
		"The method handleSETUPMethod of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLESET_PARAMETERMETHOD_FAILED,
		"The method handleSET_PARAMETERMethod of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLETEARDOWNMETHOD_FAILED,
		"The method handleTEARDOWNMethod of the RTSPSession class failed",
	SS_RTSPSESSION_SENDRTSPRESPONSE_FAILED,
		"The method sendRTSPResponse of the RTSPSession class failed",
	SS_RTSPSESSION_SEEK_FAILED,
		"The method seek of the RTSPSession class failed",
	SS_RTSPSESSION_GETCURRENTPACKETRTPTIMESTAMPANDSEQUENCENUMBER_FAILED,
		"The method getCurrentPacketRtpTimeStampAndSequenceNumber of the RTSPSession class failed",
	SS_RTSPSESSION_GETSSRC_FAILED,
		"The method getSSRC of the RTSPSession class failed",
	SS_RTSPSESSION_GETANDREMOVENEXTRTPPACKETTOSEND_FAILED,
		"The method getAndRemoveNextRTPPacketToSend of the RTSPSession class failed",
	SS_RTSPSESSION_PREFETCHNEXTPACKETS_FAILED,
		"The method prefetchNextPackets of the RTSPSession class failed",
	SS_RTSPSESSION_PREFETCHLIVEPACKET_FAILED,
		"The method prefetchLivePacket of the RTSPSession class failed",
	SS_RTSPSESSION_PREFETCHNEXTPACKETSUSINGHINTTRACK_FAILED,
		"The method prefetchNextPacketsUsingHintTrack of the RTSPSession class failed",
	SS_RTSPSESSION_PREFETCHNEXTPACKETSUSINGMEDIATRACK_FAILED,
		"The method prefetchNextPacketsUsingMediaTrack of the RTSPSession class failed",
	SS_RTSPSESSION_ACTIVETRACK_FAILED,
		"The method activeTrack of the RTSPSession class failed",
	SS_RTSPSESSION_DEACTIVETRACK_FAILED,
		"The method deactiveTrack of the RTSPSession class failed",
	SS_RTSPSESSION_NOWINMILLISECONDS_FAILED,
		"The method nowInMilliSeconds of the RTSPSession class failed",
	SS_RTSPSESSION_INITRTPSESSION_FAILED,
		"The method initRTPSession of the RTSPSession class failed",
	SS_RTSPSESSION_FINISHRTPSESSION_FAILED,
		"The method finishRTPSession of the RTSPSession class failed",
	SS_RTSPSESSION_ADDTRACKTOSTREAM_FAILED,
		"The method addTrackToStream of the RTSPSession class failed",
	SS_RTSPSESSION_DELETETRACKTOSTREAM_FAILED,
		"The method deleteTrackToStream of the RTSPSession class failed",
	SS_RTSPSESSION_PROCESSRTSPREQUEST_FAILED,
		"The method processRTSPRequest of the RTSPSession class failed",
	SS_RTSPSESSION_GETINFOFROMMP4FILE_FAILED,
		"The method getInfoFromMP4File of the RTSPSession class failed",
	SS_RTSPSESSION_CHOICEMEDIATRACKSTOSTREAM_FAILED,
		"The method choiceMediaTracksToStream of the RTSPSession class failed",
	SS_RTSPSESSION_GETPACKET_FAILED,
		"The method getPacket of the RTSPSession class failed",
	SS_RTSPSESSION_SELECTTRACKOFNEXTPACKET_FAILED,
		"The method selectTrackOfNextPacket of the RTSPSession class failed",
	SS_RTSPSESSION_SENDRTPPACKET_FAILED,
		"The method sendRTPPacket of the RTSPSession class failed",
	SS_RTSPSESSION_SENDRTPPACKETS_FAILED,
		"The method sendRTPPackets of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLERECEIVERRTCPPACKETS_FAILED,
		"The method handleReceiverRTCPPackets of the RTSPSession class failed",
	SS_RTSPSESSION_HANDLESENDERRTCPPACKETS_FAILED,
		"The method handleSenderRTCPPackets of the RTSPSession class failed",
	SS_RTSPSESSION_TRYTOREADANDPROCESSRTCPPACKETS_FAILED,
		"The method tryToReadAndProcessRTCPPackets of the RTSPSession class failed",
	SS_RTSPSESSION_SENDRTCPSRPACKET_FAILED,
		"The method sendRTCPSRPacket of the RTSPSession class failed",
	SS_RTSPSESSION_BUILDRTCPSRPACKET_FAILED,
		"The method buildRTCPSRPacket of the RTSPSession class failed",
	SS_RTSPSESSION_PROCESSRTCPPACKET_FAILED,
		"The method processRTCPPacket of the RTSPSession class failed",
	SS_RTSPSESSION_PARSEURL_FAILED,
		"The method parseURL of the RTSPSession class failed (URL: %s)",
	SS_RTSPSESSION_PARSEURLPARAMETERS_FAILED,
		"The method parseURLParameters of the RTSPSession class failed (URL parameters: %s)",
	SS_RTSPSESSION_GETFINALINFO_FAILED,
		"The method getFinalInfo of the RTSPSession class failed",
	SS_RTSPSESSION_GETAVGBITRATE_FAILED,
		"The method getAvgBitRate of the RTSPSession class failed",
	SS_RTSPSESSION_GETINFO_FAILED,
		"The method getInfo of the RTSPSession class failed",
	SS_RTSPSESSION_GETAVERAGEBANDWIDTHUSAGE_FAILED,
		"The method getAverageBandWidthUsage of the RTSPSession class failed",
	SS_RTSPSESSION_GETRANDOMOFFSETS_FAILED,
		"The method getRandomOffsets of the RTSPSession class failed",
	SS_RTSPSESSION_GETVIDEOTRACKIDENTIFIER_FAILED,
		"The method getVideoTrackIdentifier of the RTSPSession class failed",
	SS_RTSPSESSION_GETAUDIOTRACKIDENTIFIER_FAILED,
		"The method getAudioTrackIdentifier of the RTSPSession class failed",
	SS_RTSPSESSION_GETREQUESTLOG_FAILED,
		"The method getRequestLog of the RTSPSession class failed",
	SS_RTSPSESSION_RTCPMALFORMED,
		"RTCP packet malformed",
	SS_RTSPSESSION_CODECSNOTSUPPORTED,
		"Codecs not supported",
	SS_RTSPSESSION_NOMEDIATRACKS,
		"No media tracks",
	SS_RTSPSESSION_TRACKNOTFOUND,
		"Track not found",
	SS_RTSPSESSION_UNKNOWNRTSPREQUEST,
		"Unknown the '%s' RTSP request",
	SS_RTSPSESSION_ATOMNOTEXIST,
		"Atom doesn't exist (atom: %s)",
	SS_RTSPSESSION_REFERENCETRACKNOTFOUND,
		"Reference track not found",
	SS_RTSPSESSION_RTSPCONNECTIONDOWN,
		"RTSPSession identifier: %lu. RTSP connection is down. Client ip address: '%s', client port: %ld",
	SS_RTSPSESSION_DESCRIBEREQUESTWRONG,
		"RTSP DESCRIBE request wrong. DESCRIBE request: '%s'",
	SS_RTSPSESSION_PLAYREQUESTWRONG,
		"RTSP PLAY request wrong. PLAY request: '%s'",
	SS_RTSPSESSION_PAUSEREQUESTWRONG,
		"RTSP PAUSE request wrong. PAUSE request: '%s'",
	SS_RTSPSESSION_TEARDOWNREQUESTWRONG,
		"RTSP TEARDOWN request wrong. TEARDOWN request: '%s'",
	SS_RTSPSESSION_DESCRIBEURIWRONG,
		"URI wrong in DESCRIBE method. URI: %s",
	SS_RTSPSESSION_SETUPURIWRONGBECAUSETRACKNAME,
		"URI wrong in SETUP method. URI: %s, video track name: %s, audio track name: %s",
	SS_RTSPSESSION_SETUPURIWRONGBECAUSEFILENAME,
		"URI wrong in SETUP method. URI: %s",
	SS_RTSPSESSION_PLAYTIMEWRONG,
		"Timing wrong in the SETUP. Time: '%s'",
	SS_RTSPSESSION_PORTSNOTAVAILABLE,
		"Not available ports for this RTSP session. You should increase the RTP_RTCPReservedPorts or you should decrease MaxRTSPSessions in the configuration file",
	SS_RTSPSESSION_TRACKSNOMOREAVAILABLE,
		"Tracks no more available",
	SS_RTSPSESSION_TRACKNOTACTIVED,
		"Track not actived",
	SS_RTSPSESSION_TRACKNOTINITIALIZED,
		"Track not initialized",
	SS_RTSPSESSION_SESSIONLOCKED,
		"RTSP session is locked",
	SS_RTSPSESSION_RTPFREEPACKETSVECTORNOTCONSISTENCY,
		"RTP free packets vector corrupted",
	SS_RTSPSESSION_TOOEARLYTOSENDTHEPACKET,
		"Too early to send the packet. MilliSecs to wait: %lu",
	SS_RTSPSESSION_NORTSPCONNECTIONTOACCEPT_FAILED,
		"No RTSP connection to accept",
	SS_RTSPSESSION_NOPACKETPREFETCHED,
		"No RTP packet prefetched",
	SS_RTSPSESSION_WRONGLIVESDP,
		"Wrong SDP for live(%s)",
	SS_RTSPSESSION_TOOMANYLIVERTPPACKETS,
		"Too many live RTP packets",
	SS_RTSPSESSION_NORTPPACKETFOUND,
		"No RTP packet found on network %s and port %lu",
	SS_RTSPSESSION_NOMORERTPPACKETS,
		"No more RTP packets",
	SS_RTSPSESSION_NOPREFETCHEDRTPPACKET,
		"No prefetched RTP packets",
	SS_RTSPSESSION_URLPARAMETERWRONG,
		"URL parameters wrong: %s",
	SS_RTSPSESSION_URLPARAMETERNOTAPPLICABLETOLIVE,
		"URL parameter not applicable to live session: %s",
	SS_RTSPSESSION_URLPARAMETERUNKNOWN,
		"URL parameter unknown: %s",
	SS_RTSPSESSION_TOOEARLYTOSENDRTCPPACKETS,
		"Too early to send RTCP packets",
	SS_RTSPSESSION_TOOEARLYTORECEIVERTCPPACKETS,
		"Too early to receive RTCP packets",
	SS_RTSPSESSION_NOLIVERTSPSESSION,
		"No live RTSPSession",
	SS_RTSPSESSION_NOLIVESOURCEAVAILABLE,
		"No Live Source available",
	SS_RTSPSESSION_REQUESTEDPAYLOADSIZETOOBIG,
		"Requested Payload size too big: %lu, Payload size set to the max: %lu",
	SS_RTSPSESSION_STARTTIMEPARAMETERWRONG,
		"Start time parameter wrong: %ld",
	SS_RTSPSESSION_REQUESTEDSTOPTIMEREACHED,
		"Reached the requested stop time (%lf)",
	SS_RTSPSESSION_NOTHINGTOREAD,
		"RTSPSession identifier: %lu. Nothing to read",

	// PacketsSender
	SS_PACKETSSENDER_INIT_FAILED,
		"The method init of the PacketsSender class failed",
	SS_PACKETSSENDER_FINISH_FAILED,
		"The method finish of the PacketsSender class failed",
	SS_PACKETSSENDER_SETISSHUTDOWN_FAILED,
		"The method setIsShutdown of the PacketsSender class failed",
	SS_PACKETSSENDER_GETISSHUTDOWN_FAILED,
		"The method getIsShutdown of the PacketsSender class failed",
	SS_PACKETSSENDER_ADDRTSPSESSION_FAILED,
		"The method addRTSPSession of the PacketsBuilder class failed",
	SS_PACKETSSENDER_DELETERTSPSESSION_FAILED,
		"The method deleteRTSPSession of the PacketsBuilder class failed",
	SS_PACKETSSENDER_RTSPSESSIONNOTFOUND,
		"RTSP session not found",

	// PacketsBuilder
	SS_PACKETSBUILDER_INIT_FAILED,
		"The method init of the PacketsBuilder class failed",
	SS_PACKETSBUILDER_FINISH_FAILED,
		"The method finish of the PacketsBuilder class failed",
	SS_PACKETSBUILDER_SETISSHUTDOWN_FAILED,
		"The method setIsShutdown of the PacketsBuilder class failed",
	SS_PACKETSBUILDER_GETISSHUTDOWN_FAILED,
		"The method getIsShutdown of the PacketsBuilder class failed",
	SS_PACKETSBUILDER_ADDRTSPSESSION_FAILED,
		"The method addRTSPSession of the PacketsBuilder class failed",
	SS_PACKETSBUILDER_DELETERTSPSESSION_FAILED,
		"The method deleteRTSPSession of the PacketsBuilder class failed",
	SS_PACKETSBUILDER_RTSPSESSIONNOTFOUND,
		"RTSP session not found",
	SS_PACKETSBUILDER_REACHEDMAXLIVESOURCESNUMBER,
		"Reached the max number of live sources",

	// RTPOverBufferWindow
	SS_RTPOVERBUFFERWINDOW_INIT_FAILED,
		"The method init of the RTPOverBufferWindow class failed",
	SS_RTPOVERBUFFERWINDOW_FINISH_FAILED,
		"The method finish of the RTPOverBufferWindow class failed",
	SS_RTPOVERBUFFERWINDOW_ADDPACKETTOWINDOW_FAILED,
		"The method addPacketToWindow of the RTPOverBufferWindow class failed",
	SS_RTPOVERBUFFERWINDOW_EMPTYOUTWINDOW_FAILED,
		"The method emptyOutWindow of the RTPOverBufferWindow class failed",
	SS_RTPOVERBUFFERWINDOW_MARKBEGINNINGOFWRITEBURST_FAILED,
		"The method markBeginningOfWriteBurst of the RTPOverBufferWindow class failed",
	SS_RTPOVERBUFFERWINDOW_RESETOVERBUFFERWINDOW_FAILED,
		"The method resetOverBufferWindow of the RTPOverBufferWindow class failed",
	SS_RTPOVERBUFFERWINDOW_PACKETBEFOREWINDOW,
		"Packet is before the window",
	SS_RTPOVERBUFFERWINDOW_WINDOWVARIABLESNOTCONSISTENT,
		"Window variables are not consistent",

	// BeginningHookHTTPGetThread
	SS_BEGINNINGHOOKHTTPGETTHREAD_INIT_FAILED,
		"The method init of the BeginningHookHTTPGetThread class failed",
	SS_BEGINNINGHOOKHTTPGETTHREAD_FINISH_FAILED,
		"The method finish of the BeginningHookHTTPGetThread class failed",
	SS_BEGINNINGHOOKHTTPGETTHREAD_BEGINNINGHOOKHTTPGETRESPONSEWRONG,
		"Wrong authorization HTTP get response: %s",

	// windowsService
	SS_REPORTSTATUSTOSCMGR_FAILED,
		"ReportStatusToSCMgr failed",

	// common
	SS_ACTIVATION_WRONG,
		"Activation wrong",
	SS_ENVIRONMENTVARIABLE_NOTDEFINED,
		"The '%s' environment variable is not defined",
	SS_RTSPSESSION_WRONGSTATE,
		"RTSPSession identifier: %lu. The RTSP session cannot perform the %s command. RTSP state: %lu",
	SS_CORBA_GENERICERROR,
		"CORBA generic error",
	SS_CONFIGITEMWRONG,
		"Configuration item value wrong. Section: %s, item: %s",
	SS_NEW_FAILED,
		"new failed",
	SS_MKDIR_FAILED,
		"mkdir failed. Directory: %s",
	SS_RMDIR_FAILED,
		"rmdir failed. Directory: %s, errno: %ld",
	SS_GETHOSTNAME_FAILED,
		"gethostname failed. Error: %ld",
	SS_UNAME_FAILED,
		"uname failed",
	SS_UNLINK_FAILED,
		"unlink failed. File name: %s",
	SS_OPEN_FAILED,
		"open failed. File name: %s",
	SS_WRITE_FAILED,
		"write failed",
	SS_CLOSE_FAILED,
		"close failed",
	SS_LSTAT_FAILED,
		"lstat failed. Entry: %s",
	SS_SSCANF_FAILED,
		"sscanf failed",
	SS_FORK_FAILED,
		"fork failed",
	SS_CREATEPROCESS_FAILED,
		"CreateProcess failed",
	SS_LOCALTIME_R_FAILED,
		"localtime_r failed"

	// Insert here other errors...

} ;

