# - Try to find the Catralibraries library
# Once done this will define
#
# CATRALIBRARIES_FOUND - system has the CatraLibraries library
# CATRALIBRARIES_INCLUDE_DIR - the CatraLibraries include directory
# CATRALIBRARIES_LIBRARIES - The libraries needed to use CatraLibraries
# Copyright (c) 2015, Giuliano Catrambone, <giulianoc@catrasoftware.it>
#
# Redistribution and use is allowed according to the terms of the BSD license.
# For details see the accompanying COPYING-CMAKE-SCRIPTS file.

IF(CATRALIBRARIES_LIBRARIES)
	SET(CatraLibraries_FIND_QUIETLY TRUE)
ENDIF(CATRALIBRARIES_LIBRARIES)

FIND_PATH(CATRALIBRARIES_INCLUDE_DIR ErrMsgBase.h )
FIND_LIBRARY(CATRALIBRARIES_LIBRARIES NAMES ErrMsg )

IF(CATRALIBRARIES_INCLUDE_DIR AND CATRALIBRARIES_LIBRARIES)
	SET(CATRALIBRARIES_FOUND TRUE)
ELSE(CATRALIBRARIES_INCLUDE_DIR AND CATRALIBRARIES_LIBRARIES)
	SET(CATRALIBRARIES_FOUND FALSE)
ENDIF (CATRALIBRARIES_INCLUDE_DIR AND CATRALIBRARIES_LIBRARIES)

IF (CATRALIBRARIES_FOUND)
	IF (NOT CatraLibraries_FIND_QUIETLY)
		MESSAGE(STATUS "Found CatraLibraries: ${CATRALIBRARIES_LIBRARIES}")
	ENDIF (NOT CatraLibraries_FIND_QUIETLY)
ELSE (CATRALIBRARIES_FOUND)
	IF (CatraLibraries_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could NOT find CatraLibraries")
	ENDIF (CatraLibraries_FIND_REQUIRED)
ENDIF (CATRALIBRARIES_FOUND)

MARK_AS_ADVANCED(CATRALIBRARIES_INCLUDE_DIR CATRALIBRARIES_LIBRARIES)

